// THIS IS AUTOGENERATED FILE. DO NOT EDIT
module.exports = [
  {
    "glyphs": [
      {
        "search": [
          "profile",
          "contact",
          "user",
          "add"
        ],
        "code": 57345,
        "file": "add-contact-add-user",
        "css": "user-add"
      },
      {
        "search": [
          "address"
        ],
        "code": 57346,
        "file": "address",
        "css": "address"
      },
      {
        "search": [
          "add",
          "list"
        ],
        "code": 57347,
        "file": "add-to-list",
        "css": "list-add"
      },
      {
        "search": [
          "alert",
          "bell",
          "jingle"
        ],
        "code": 128276,
        "file": "alert",
        "css": "bell"
      },
      {
        "search": [
          "attach",
          "clip"
        ],
        "code": 57348,
        "file": "attach",
        "css": "attach"
      },
      {
        "search": [
          "back"
        ],
        "code": 57349,
        "file": "back",
        "css": "back"
      },
      {
        "search": [
          "back"
        ],
        "code": 57397,
        "file": "back-alt",
        "css": "back-alt"
      },
      {
        "search": [
          "block",
          "deny"
        ],
        "code": 128683,
        "file": "block",
        "css": "block"
      },
      {
        "search": [
          "broadcast",
          "wifi"
        ],
        "code": 57350,
        "file": "broadcast",
        "css": "wifi"
      },
      {
        "search": [
          "calendar"
        ],
        "code": 128197,
        "file": "calendar",
        "css": "calendar"
      },
      {
        "search": [
          "camera",
          "photo"
        ],
        "code": 128247,
        "file": "camera",
        "css": "camera"
      },
      {
        "search": [
          "target"
        ],
        "code": 127919,
        "file": "center-crosshair",
        "css": "target"
      },
      {
        "search": [
          "chat",
          "talk"
        ],
        "code": 57351,
        "file": "chat",
        "css": "chat"
      },
      {
        "search": [
          "close",
          "cancel"
        ],
        "code": 10005,
        "file": "check-not-ok",
        "css": "close"
      },
      {
        "search": [
          "check",
          "mark"
        ],
        "code": 10003,
        "file": "check-ok",
        "css": "check"
      },
      {
        "search": [
          "cancel",
          "close"
        ],
        "code": 10006,
        "file": "close-circle",
        "css": "cancel"
      },
      {
        "search": [
          "comment",
          "reply"
        ],
        "code": 57352,
        "file": "comment",
        "css": "comment"
      },
      {
        "search": [
          "compass"
        ],
        "code": 57353,
        "file": "compass",
        "css": "compass"
      },
      {
        "search": [
          "contact",
          "card",
          "vcard"
        ],
        "code": 57354,
        "file": "contact-card",
        "css": "vcard"
      },
      {
        "search": [
          "profile",
          "contact",
          "user"
        ],
        "code": 128100,
        "file": "contact-user",
        "css": "user"
      },
      {
        "search": [
          "users",
          "contacts",
          "friends"
        ],
        "code": 128101,
        "file": "contacts-users",
        "css": "users"
      },
      {
        "search": [
          "direction"
        ],
        "code": 57355,
        "file": "direction",
        "css": "direction"
      },
      {
        "search": [
          "mail",
          "email"
        ],
        "code": 9993,
        "file": "email",
        "css": "mail"
      },
      {
        "search": [
          "export"
        ],
        "code": 57356,
        "file": "export",
        "css": "export"
      },
      {
        "search": [
          "flag"
        ],
        "code": 9873,
        "file": "flag",
        "css": "flag"
      },
      {
        "search": [
          "flash",
          "bolt"
        ],
        "code": 9889,
        "file": "flash",
        "css": "flash"
      },
      {
        "search": [
          "flight",
          "plane",
          "airplane"
        ],
        "code": 9992,
        "file": "flight",
        "css": "flight"
      },
      {
        "search": [
          "forward"
        ],
        "code": 10150,
        "file": "forward",
        "css": "forward"
      },
      {
        "search": [
          "google",
          "circles"
        ],
        "code": 57357,
        "file": "google-circles",
        "css": "google-circles"
      },
      {
        "search": [
          "heart"
        ],
        "code": 9829,
        "file": "heart",
        "css": "heart"
      },
      {
        "search": [
          "heart"
        ],
        "code": 9825,
        "file": "heart-outlined",
        "css": "heart-empty"
      },
      {
        "search": [
          "help"
        ],
        "code": 10067,
        "file": "help",
        "css": "help"
      },
      {
        "search": [
          "help"
        ],
        "code": 57358,
        "file": "help-circle",
        "css": "help-circle"
      },
      {
        "search": [
          "image",
          "list"
        ],
        "code": 9871,
        "file": "image-list",
        "css": "image-list"
      },
      {
        "search": [
          "info"
        ],
        "code": 8505,
        "file": "info",
        "css": "info"
      },
      {
        "search": [
          "info"
        ],
        "code": 57359,
        "file": "info-circle",
        "css": "info-circle"
      },
      {
        "search": [
          "leaf"
        ],
        "code": 127810,
        "file": "leaf",
        "css": "leaf"
      },
      {
        "search": [
          "down"
        ],
        "code": 8627,
        "file": "level-down",
        "css": "level-down"
      },
      {
        "search": [
          "lifebuoy"
        ],
        "code": 57360,
        "file": "lifebuoy",
        "css": "lifebuoy"
      },
      {
        "search": [
          "thumbs",
          "up",
          "like",
          "vote"
        ],
        "code": 128221,
        "file": "like-thumbs-up",
        "css": "thumbs-up"
      },
      {
        "search": [
          "link",
          "url"
        ],
        "code": 128279,
        "file": "link",
        "css": "link"
      },
      {
        "search": [
          "list"
        ],
        "code": 9776,
        "file": "list",
        "css": "list"
      },
      {
        "search": [
          "location",
          "marker"
        ],
        "code": 57361,
        "file": "location",
        "css": "location"
      },
      {
        "search": [
          "lock"
        ],
        "code": 128274,
        "file": "lock",
        "css": "lock"
      },
      {
        "search": [
          "down"
        ],
        "code": 57362,
        "file": "map",
        "css": "map"
      },
      {
        "search": [
          "mic"
        ],
        "code": 127908,
        "file": "mic",
        "css": "mic"
      },
      {
        "search": [
          "minus"
        ],
        "code": 10134,
        "file": "minus",
        "css": "minus"
      },
      {
        "search": [
          "minus"
        ],
        "code": 57363,
        "file": "minus-circle",
        "css": "minus-circle"
      },
      {
        "search": [
          "mobile",
          "iphone"
        ],
        "code": 128241,
        "file": "mobile",
        "css": "mobile"
      },
      {
        "search": [
          "mouse",
          "website"
        ],
        "code": 57364,
        "file": "mouse-website",
        "css": "mouse"
      },
      {
        "search": [
          "movie",
          "video"
        ],
        "code": 127916,
        "file": "movie",
        "css": "film"
      },
      {
        "search": [
          "music",
          "note"
        ],
        "code": 127925,
        "file": "music",
        "css": "music"
      },
      {
        "search": [
          "tag",
          "price",
          "offer"
        ],
        "code": 57365,
        "file": "offer-price-tag",
        "css": "tag"
      },
      {
        "search": [
          "palette"
        ],
        "code": 127912,
        "file": "palette",
        "css": "palette"
      },
      {
        "search": [
          "phone",
          "telephone"
        ],
        "code": 128222,
        "file": "phone",
        "css": "phone"
      },
      {
        "search": [
          "plus"
        ],
        "code": 10133,
        "file": "plus",
        "css": "plus"
      },
      {
        "search": [
          "plus"
        ],
        "code": 57366,
        "file": "plus-circle",
        "css": "plus-circle"
      },
      {
        "search": [
          "print"
        ],
        "code": 57367,
        "file": "print",
        "css": "print"
      },
      {
        "search": [
          "quote"
        ],
        "code": 10078,
        "file": "quote",
        "css": "quote-right"
      },
      {
        "search": [
          "reload"
        ],
        "code": 10226,
        "file": "reload-CCW",
        "css": "reload-ccw"
      },
      {
        "search": [
          "reload"
        ],
        "code": 10227,
        "file": "reload-CW",
        "css": "reload-cw"
      },
      {
        "search": [
          "reply"
        ],
        "code": 57368,
        "file": "reply",
        "css": "reply"
      },
      {
        "search": [
          "reply"
        ],
        "code": 57369,
        "file": "reply-to-all",
        "css": "reply-all"
      },
      {
        "search": [
          "retweet"
        ],
        "code": 57370,
        "file": "retweet",
        "css": "retweet"
      },
      {
        "search": [
          "rss"
        ],
        "code": 57371,
        "file": "rss",
        "css": "rss"
      },
      {
        "search": [
          "search",
          "find"
        ],
        "code": 128269,
        "file": "classic-search",
        "css": "search"
      },
      {
        "search": [
          "search",
          "find"
        ],
        "code": 128270,
        "file": "search",
        "css": "search-alt"
      },
      {
        "search": [
          "settings",
          "cog"
        ],
        "code": 9881,
        "file": "settings",
        "css": "settings"
      },
      {
        "search": [
          "share"
        ],
        "code": 57372,
        "file": "share",
        "css": "share"
      },
      {
        "search": [
          "basket",
          "shopping",
          "cart"
        ],
        "code": 57344,
        "file": "shopping-bag",
        "css": "shopping-cart"
      },
      {
        "search": [
          "shuffle"
        ],
        "code": 128256,
        "file": "shuffle",
        "css": "shuffle"
      },
      {
        "search": [
          "moon",
          "sleep"
        ],
        "code": 9789,
        "file": "sleep",
        "css": "moon"
      },
      {
        "search": [
          "star"
        ],
        "code": 9733,
        "file": "star",
        "css": "star"
      },
      {
        "search": [
          "star"
        ],
        "code": 9734,
        "file": "star-outlined",
        "css": "star-empty"
      },
      {
        "search": [
          "clock",
          "time"
        ],
        "code": 128340,
        "file": "time-clock",
        "css": "clock"
      },
      {
        "search": [
          "clock",
          "hourglass",
          "busy",
          "wait"
        ],
        "code": 9203,
        "file": "time-glass",
        "css": "hourglass"
      },
      {
        "search": [
          "top",
          "trophy"
        ],
        "code": 127945,
        "file": "top-list",
        "css": "top-list"
      },
      {
        "search": [
          "lock",
          "unlock"
        ],
        "code": 128275,
        "file": "unlocked",
        "css": "lock-open"
      },
      {
        "search": [
          "eye",
          "subscribe"
        ],
        "code": 57373,
        "file": "view-eye",
        "css": "eye"
      },
      {
        "search": [
          "warning"
        ],
        "code": 9888,
        "file": "warning",
        "css": "warning"
      },
      {
        "search": [
          "pencil",
          "write"
        ],
        "code": 9987,
        "file": "write-new",
        "css": "pencil"
      },
      {
        "search": [
          "archive"
        ],
        "code": 57374,
        "file": "archive",
        "css": "archive"
      },
      {
        "search": [
          "arrow",
          "down"
        ],
        "code": 57376,
        "file": "down-circle-arrow",
        "css": "arrow-down-circle2"
      },
      {
        "search": [
          "arrow",
          "left"
        ],
        "code": 57377,
        "file": "left-circle-arrow",
        "css": "arrow-left-circle2"
      },
      {
        "search": [
          "arrow",
          "right"
        ],
        "code": 57378,
        "file": "right-circle-arrow",
        "css": "arrow-right-circle2"
      },
      {
        "search": [
          "arrow",
          "up"
        ],
        "code": 57379,
        "file": "up-circle-arrow",
        "css": "arrow-up-circle2"
      },
      {
        "search": [
          "arrow",
          "down"
        ],
        "code": 57380,
        "file": "open-arrow-down",
        "css": "arrow-down-open"
      },
      {
        "search": [
          "arrow",
          "left"
        ],
        "code": 57381,
        "file": "open-arrow-left",
        "css": "arrow-left-open"
      },
      {
        "search": [
          "arrow",
          "right"
        ],
        "code": 57382,
        "file": "open-arrow-right",
        "css": "arrow-right-open"
      },
      {
        "search": [
          "arrow",
          "up"
        ],
        "code": 57383,
        "file": "open-arrow-up",
        "css": "arrow-up-open"
      },
      {
        "search": [
          "arrow",
          "down"
        ],
        "code": 11015,
        "file": "thin-arrow-down",
        "css": "arrow-down-thin"
      },
      {
        "search": [
          "arrow",
          "left"
        ],
        "code": 11013,
        "file": "thin-arrow-left",
        "css": "arrow-left-thin"
      },
      {
        "search": [
          "arrow",
          "right"
        ],
        "code": 10145,
        "file": "thin-arrow-right",
        "css": "arrow-right-thin"
      },
      {
        "search": [
          "arrow",
          "up"
        ],
        "code": 11014,
        "file": "thin-arrow-up",
        "css": "arrow-up-thin"
      },
      {
        "search": [
          "arrow",
          "down"
        ],
        "code": 9662,
        "file": "direction-arrow-down",
        "css": "arrow-down-dir"
      },
      {
        "search": [
          "arrow",
          "left"
        ],
        "code": 9666,
        "file": "direction-arrow-left",
        "css": "arrow-left-dir"
      },
      {
        "search": [
          "arrow",
          "right"
        ],
        "code": 9656,
        "file": "direction-arrow-right",
        "css": "arrow-right-dir"
      },
      {
        "search": [
          "arrow",
          "up"
        ],
        "code": 9652,
        "file": "direction-arrow-up",
        "css": "arrow-up-dir"
      },
      {
        "search": [
          "arrow",
          "down"
        ],
        "code": 58544,
        "file": "bold-down-arrow",
        "css": "arrow-down-bold"
      },
      {
        "search": [
          "arrow",
          "left"
        ],
        "code": 58541,
        "file": "bold-left-arrow",
        "css": "arrow-left-bold"
      },
      {
        "search": [
          "arrow",
          "right"
        ],
        "code": 58542,
        "file": "bold-right-arrow",
        "css": "arrow-right-bold"
      },
      {
        "search": [
          "arrow",
          "up"
        ],
        "code": 58543,
        "file": "bold-up-arrow",
        "css": "arrow-up-bold"
      },
      {
        "search": [
          "arrow",
          "down"
        ],
        "code": 8595,
        "file": "down-arrow",
        "css": "arrow-down"
      },
      {
        "search": [
          "arrow",
          "left"
        ],
        "code": 8592,
        "file": "left-arrow",
        "css": "arrow-left"
      },
      {
        "search": [
          "arrow",
          "right"
        ],
        "code": 8594,
        "file": "right-arrow",
        "css": "arrow-right"
      },
      {
        "search": [
          "arrow",
          "up"
        ],
        "code": 8593,
        "file": "up-arrow",
        "css": "arrow-up"
      },
      {
        "search": [
          "progress",
          "charge"
        ],
        "code": 57392,
        "file": "charge-empty",
        "css": "progress-0"
      },
      {
        "search": [
          "progress",
          "charge"
        ],
        "code": 57393,
        "file": "charge-one-third",
        "css": "progress-1"
      },
      {
        "search": [
          "progress",
          "charge"
        ],
        "code": 57394,
        "file": "charge-two-thirds",
        "css": "progress-2"
      },
      {
        "search": [
          "progress",
          "charge"
        ],
        "code": 57395,
        "file": "charge-full",
        "css": "progress-3"
      },
      {
        "search": [
          "play",
          "player"
        ],
        "code": 9654,
        "file": "play",
        "css": "play"
      },
      {
        "search": [
          "stop",
          "player"
        ],
        "code": 9642,
        "file": "stop",
        "css": "stop"
      },
      {
        "search": [
          "pause",
          "player"
        ],
        "code": 9097,
        "file": "paus",
        "css": "pause"
      },
      {
        "search": [
          "record",
          "player"
        ],
        "code": 9899,
        "file": "record",
        "css": "record"
      },
      {
        "search": [
          "right",
          "player"
        ],
        "code": 9197,
        "file": "jump-to-end",
        "css": "right-end"
      },
      {
        "search": [
          "left",
          "player"
        ],
        "code": 9198,
        "file": "jump-to-start",
        "css": "left-start"
      },
      {
        "search": [
          "right",
          "player"
        ],
        "code": 9193,
        "file": "fast-forward",
        "css": "right-ff"
      },
      {
        "search": [
          "left",
          "player"
        ],
        "code": 9194,
        "file": "fast-backward",
        "css": "left-fb"
      },
      {
        "search": [
          "book"
        ],
        "code": 128214,
        "file": "book",
        "css": "book-open"
      },
      {
        "search": [
          "bookmark"
        ],
        "code": 128278,
        "file": "bookmark",
        "css": "bookmark"
      },
      {
        "search": [
          "battery"
        ],
        "code": 128267,
        "file": "battery",
        "css": "battery"
      },
      {
        "search": [
          "back",
          "time"
        ],
        "code": 57408,
        "file": "back-in-time",
        "css": "back-in-time"
      },
      {
        "search": [
          "home"
        ],
        "code": 8962,
        "file": "home",
        "css": "home"
      },
      {
        "search": [
          "dot"
        ],
        "code": 57424,
        "file": "dot",
        "css": "dot"
      },
      {
        "search": [
          "dot"
        ],
        "code": 57425,
        "file": "dots-two",
        "css": "dot-2"
      },
      {
        "search": [
          "dot"
        ],
        "code": 57426,
        "file": "dots-three",
        "css": "dot-3"
      },
      {
        "search": [
          "idea",
          "lamp",
          "light"
        ],
        "code": 128161,
        "file": "light-bulb",
        "css": "lamp"
      },
      {
        "search": [
          "light",
          "dim",
          "bright"
        ],
        "code": 128261,
        "file": "light-down",
        "css": "light-down"
      },
      {
        "search": [
          "light",
          "dim",
          "bright"
        ],
        "code": 128262,
        "file": "light-up",
        "css": "light-up"
      },
      {
        "search": [
          "trash"
        ],
        "code": 57562,
        "file": "trash",
        "css": "trash"
      },
      {
        "search": [
          "doc",
          "article"
        ],
        "code": 57416,
        "file": "document",
        "css": "doc"
      },
      {
        "search": [
          "doc",
          "article"
        ],
        "code": 57417,
        "file": "documents",
        "css": "docs"
      },
      {
        "search": [
          "doc",
          "article"
        ],
        "code": 57418,
        "file": "landscape-documents",
        "css": "docs-landscape"
      },
      {
        "search": [
          "doc",
          "text",
          "article"
        ],
        "code": 128196,
        "file": "text-document",
        "css": "doc-text"
      },
      {
        "search": [
          "volume",
          "sound",
          "mute"
        ],
        "code": 128263,
        "file": "mute",
        "css": "volume-off"
      },
      {
        "search": [
          "volume",
          "sound"
        ],
        "code": 128266,
        "file": "sound",
        "css": "volume-up"
      },
      {
        "search": [
          "volume",
          "sound"
        ],
        "code": 57431,
        "file": "volume",
        "css": "volume"
      },
      {
        "search": [
          "cloud"
        ],
        "code": 9729,
        "file": "cloud",
        "css": "cloud"
      },
      {
        "search": [
          "keyboard"
        ],
        "code": 9000,
        "file": "keyboard",
        "css": "keyboard"
      },
      {
        "search": [
          "folder"
        ],
        "code": 128193,
        "file": "folder",
        "css": "folder"
      },
      {
        "search": [
          "download"
        ],
        "code": 57410,
        "file": "download",
        "css": "download"
      },
      {
        "search": [],
        "code": 57411,
        "file": "upload",
        "css": "upload"
      },
      {
        "search": [
          "upload",
          "cloud"
        ],
        "code": 57413,
        "file": "upload-to-cloud",
        "css": "upload-cloud"
      },
      {
        "search": [
          "code"
        ],
        "code": 57439,
        "file": "code",
        "css": "code"
      },
      {
        "search": [
          "popup"
        ],
        "code": 57440,
        "file": "popup",
        "css": "popup"
      },
      {
        "search": [
          "publish"
        ],
        "code": 57441,
        "file": "publish",
        "css": "publish"
      },
      {
        "search": [
          "pen",
          "feather"
        ],
        "code": 57442,
        "file": "feather",
        "css": "feather"
      },
      {
        "search": [
          "resize",
          "fullscreen"
        ],
        "code": 57443,
        "file": "full-screen",
        "css": "resize-full"
      },
      {
        "search": [
          "resize"
        ],
        "code": 57444,
        "file": "small-screen",
        "css": "resize-small"
      },
      {
        "search": [
          "globe"
        ],
        "code": 57445,
        "file": "globe",
        "css": "globe"
      },
      {
        "search": [
          "cd",
          "vinyl"
        ],
        "code": 128191,
        "file": "vinyl-record",
        "css": "cd"
      },
      {
        "search": [
          "tv",
          "screen",
          "monitor"
        ],
        "code": 128187,
        "file": "tv-screen",
        "css": "monitor"
      },
      {
        "search": [
          "image"
        ],
        "code": 127748,
        "file": "image",
        "css": "image"
      },
      {
        "search": [
          "arrow"
        ],
        "code": 57432,
        "file": "select-box-arrow",
        "css": "arrow-combo"
      },
      {
        "search": [
          "window"
        ],
        "code": 57433,
        "file": "browser",
        "css": "window"
      },
      {
        "search": [
          "song",
          "music",
          "sound"
        ],
        "code": 57434,
        "file": "song",
        "css": "song"
      },
      {
        "search": [
          "inbox"
        ],
        "code": 57435,
        "file": "inbox",
        "css": "inbox"
      },
      {
        "search": [
          "install"
        ],
        "code": 57436,
        "file": "install",
        "css": "install"
      },
      {
        "search": [
          "bag"
        ],
        "code": 57437,
        "file": "suitecase",
        "css": "bag"
      },
      {
        "search": [
          "net"
        ],
        "code": 57438,
        "file": "network",
        "css": "net"
      },
      {
        "search": [
          "creative",
          "commons"
        ],
        "code": 57731,
        "file": "creative-commons",
        "css": "cc"
      },
      {
        "search": [],
        "code": 57728,
        "file": "entypo-square",
        "css": "logo-entypo"
      },
      {
        "search": [],
        "code": 57729,
        "file": "sweden",
        "css": "flag-sw"
      },
      {
        "search": [],
        "code": 57730,
        "file": "db-signature",
        "css": "logo-db"
      }
    ],
    "font": {
      "fontname": "entypo",
      "descent": 410,
      "copyright": "Copyright (C) 2012 by Daniel Bruce",
      "familyname": "Entypo",
      "weight": "Medium",
      "version": "1.0",
      "fullname": "Entypo",
      "ascent": 1638
    },
    "meta": {
      "github": "https://github.com/danielbruce/entypo",
      "licence_url": "http://scripts.sil.org/OFL",
      "licence": "SIL",
      "author": "Daniel Buce",
      "twitter": "http://twitter.com/danielbruce_",
      "email": "daniel@precinct.net",
      "css_prefix": "icon-",
      "homepage": "http://www.entypo.com",
      "dribble": "http://dribbble.com/danielbruce",
      "columns": 4
    },
    "id": 0
  },
  {
    "glyphs": [
      {
        "code": 61440,
        "css": "glyph1",
        "file": "glyph1"
      },
      {
        "code": 61441,
        "css": "glyph2",
        "file": "glyph2"
      },
      {
        "code": 61442,
        "css": "glyph3",
        "file": "glyph3"
      },
      {
        "code": 61443,
        "css": "glyph4",
        "file": "glyph4"
      },
      {
        "code": 61444,
        "css": "glyph5",
        "file": "glyph5"
      },
      {
        "code": 61445,
        "css": "glyph6",
        "file": "glyph6"
      },
      {
        "code": 61446,
        "css": "glyph7",
        "file": "glyph7"
      },
      {
        "code": 61447,
        "css": "glyph8",
        "file": "glyph8"
      },
      {
        "code": 61448,
        "css": "glyph9",
        "file": "glyph9"
      },
      {
        "code": 61449,
        "css": "glyph10",
        "file": "glyph10"
      },
      {
        "code": 61450,
        "css": "glyph11",
        "file": "glyph11"
      },
      {
        "code": 61451,
        "css": "glyph12",
        "file": "glyph12"
      },
      {
        "code": 61452,
        "css": "glyph13",
        "file": "glyph13"
      },
      {
        "code": 61453,
        "css": "glyph14",
        "file": "glyph14"
      },
      {
        "code": 61454,
        "css": "glyph15",
        "file": "glyph15"
      },
      {
        "code": 61456,
        "css": "glyph16",
        "file": "glyph16"
      },
      {
        "code": 61457,
        "css": "glyph17",
        "file": "glyph17"
      },
      {
        "code": 61458,
        "css": "glyph18",
        "file": "glyph18"
      },
      {
        "code": 61459,
        "css": "glyph19",
        "file": "glyph19"
      },
      {
        "code": 61460,
        "css": "glyph20",
        "file": "glyph20"
      },
      {
        "code": 61461,
        "css": "glyph21",
        "file": "glyph21"
      },
      {
        "code": 61462,
        "css": "glyph22",
        "file": "glyph22"
      },
      {
        "code": 61463,
        "css": "glyph23",
        "file": "glyph23"
      },
      {
        "code": 61464,
        "css": "glyph24",
        "file": "glyph24"
      },
      {
        "code": 61465,
        "css": "glyph25",
        "file": "glyph25"
      },
      {
        "code": 61466,
        "css": "glyph26",
        "file": "glyph26"
      },
      {
        "code": 61467,
        "css": "glyph27",
        "file": "glyph27"
      },
      {
        "code": 61468,
        "css": "glyph28",
        "file": "glyph28"
      },
      {
        "code": 61469,
        "css": "glyph29",
        "file": "glyph29"
      },
      {
        "code": 61470,
        "css": "glyph30",
        "file": "glyph30"
      },
      {
        "code": 61473,
        "css": "glyph31",
        "file": "glyph31"
      },
      {
        "code": 61474,
        "css": "glyph32",
        "file": "glyph32"
      },
      {
        "code": 61475,
        "css": "glyph33",
        "file": "glyph33"
      },
      {
        "code": 61476,
        "css": "glyph34",
        "file": "glyph34"
      },
      {
        "code": 61477,
        "css": "glyph35",
        "file": "glyph35"
      },
      {
        "code": 61478,
        "css": "glyph36",
        "file": "glyph36"
      },
      {
        "code": 61479,
        "css": "glyph37",
        "file": "glyph37"
      },
      {
        "code": 61480,
        "css": "glyph38",
        "file": "glyph38"
      },
      {
        "code": 61481,
        "css": "glyph39",
        "file": "glyph39"
      },
      {
        "code": 61482,
        "css": "glyph40",
        "file": "glyph40"
      },
      {
        "code": 61483,
        "css": "glyph41",
        "file": "glyph41"
      },
      {
        "code": 61484,
        "css": "glyph42",
        "file": "glyph42"
      },
      {
        "code": 61485,
        "css": "glyph43",
        "file": "glyph43"
      },
      {
        "code": 61486,
        "css": "glyph44",
        "file": "glyph44"
      },
      {
        "code": 61487,
        "css": "glyph45",
        "file": "glyph45"
      },
      {
        "code": 61488,
        "css": "glyph46",
        "file": "glyph46"
      },
      {
        "code": 61489,
        "css": "glyph47",
        "file": "glyph47"
      },
      {
        "code": 61490,
        "css": "glyph48",
        "file": "glyph48"
      },
      {
        "code": 61491,
        "css": "glyph49",
        "file": "glyph49"
      },
      {
        "code": 61492,
        "css": "glyph50",
        "file": "glyph50"
      },
      {
        "code": 61493,
        "css": "glyph51",
        "file": "glyph51"
      },
      {
        "code": 61494,
        "css": "glyph52",
        "file": "glyph52"
      },
      {
        "code": 61495,
        "css": "glyph53",
        "file": "glyph53"
      },
      {
        "code": 61496,
        "css": "glyph54",
        "file": "glyph54"
      },
      {
        "code": 61497,
        "css": "glyph55",
        "file": "glyph55"
      },
      {
        "code": 61498,
        "css": "glyph56",
        "file": "glyph56"
      },
      {
        "code": 61499,
        "css": "glyph57",
        "file": "glyph57"
      },
      {
        "code": 61500,
        "css": "glyph58",
        "file": "glyph58"
      },
      {
        "code": 61501,
        "css": "glyph59",
        "file": "glyph59"
      },
      {
        "code": 61502,
        "css": "glyph60",
        "file": "glyph60"
      },
      {
        "code": 61504,
        "css": "glyph61",
        "file": "glyph61"
      },
      {
        "code": 61505,
        "css": "glyph62",
        "file": "glyph62"
      },
      {
        "code": 61506,
        "css": "glyph63",
        "file": "glyph63"
      },
      {
        "code": 61507,
        "css": "glyph64",
        "file": "glyph64"
      },
      {
        "code": 61508,
        "css": "glyph65",
        "file": "glyph65"
      },
      {
        "code": 61509,
        "css": "glyph66",
        "file": "glyph66"
      },
      {
        "code": 61510,
        "css": "glyph67",
        "file": "glyph67"
      },
      {
        "code": 61511,
        "css": "glyph68",
        "file": "glyph68"
      },
      {
        "code": 61512,
        "css": "glyph69",
        "file": "glyph69"
      },
      {
        "code": 61513,
        "css": "glyph70",
        "file": "glyph70"
      },
      {
        "code": 61514,
        "css": "glyph71",
        "file": "glyph71"
      },
      {
        "code": 61515,
        "css": "glyph72",
        "file": "glyph72"
      },
      {
        "code": 61516,
        "css": "glyph73",
        "file": "glyph73"
      },
      {
        "code": 61517,
        "css": "glyph74",
        "file": "glyph74"
      },
      {
        "code": 61518,
        "css": "glyph75",
        "file": "glyph75"
      },
      {
        "code": 61520,
        "css": "glyph76",
        "file": "glyph76"
      },
      {
        "code": 61521,
        "css": "glyph77",
        "file": "glyph77"
      },
      {
        "code": 61522,
        "css": "glyph78",
        "file": "glyph78"
      },
      {
        "code": 61523,
        "css": "glyph79",
        "file": "glyph79"
      },
      {
        "code": 61524,
        "css": "glyph80",
        "file": "glyph80"
      },
      {
        "code": 61525,
        "css": "glyph81",
        "file": "glyph81"
      },
      {
        "code": 61526,
        "css": "glyph82",
        "file": "glyph82"
      },
      {
        "code": 61527,
        "css": "glyph83",
        "file": "glyph83"
      },
      {
        "code": 61528,
        "css": "glyph84",
        "file": "glyph84"
      },
      {
        "code": 61529,
        "css": "glyph85",
        "file": "glyph85"
      },
      {
        "code": 61530,
        "css": "glyph86",
        "file": "glyph86"
      },
      {
        "code": 61531,
        "css": "glyph87",
        "file": "glyph87"
      },
      {
        "code": 61532,
        "css": "glyph88",
        "file": "glyph88"
      },
      {
        "code": 61533,
        "css": "glyph89",
        "file": "glyph89"
      },
      {
        "code": 61534,
        "css": "glyph90",
        "file": "glyph90"
      },
      {
        "code": 61536,
        "css": "glyph91",
        "file": "glyph91"
      },
      {
        "code": 61537,
        "css": "glyph92",
        "file": "glyph92"
      },
      {
        "code": 61538,
        "css": "glyph93",
        "file": "glyph93"
      },
      {
        "code": 61539,
        "css": "glyph94",
        "file": "glyph94"
      },
      {
        "code": 61540,
        "css": "glyph95",
        "file": "glyph95"
      },
      {
        "code": 61541,
        "css": "glyph96",
        "file": "glyph96"
      },
      {
        "code": 61542,
        "css": "glyph97",
        "file": "glyph97"
      },
      {
        "code": 61543,
        "css": "glyph98",
        "file": "glyph98"
      },
      {
        "code": 61544,
        "css": "glyph99",
        "file": "glyph99"
      },
      {
        "code": 61545,
        "css": "glyph100",
        "file": "glyph100"
      },
      {
        "code": 61546,
        "css": "glyph101",
        "file": "glyph101"
      },
      {
        "code": 61547,
        "css": "glyph102",
        "file": "glyph102"
      },
      {
        "code": 61548,
        "css": "glyph103",
        "file": "glyph103"
      },
      {
        "code": 61549,
        "css": "glyph104",
        "file": "glyph104"
      },
      {
        "code": 61550,
        "css": "glyph105",
        "file": "glyph105"
      },
      {
        "code": 61552,
        "css": "glyph106",
        "file": "glyph106"
      },
      {
        "code": 61553,
        "css": "glyph107",
        "file": "glyph107"
      },
      {
        "code": 61554,
        "css": "glyph108",
        "file": "glyph108"
      },
      {
        "code": 61555,
        "css": "glyph109",
        "file": "glyph109"
      },
      {
        "code": 61556,
        "css": "glyph110",
        "file": "glyph110"
      },
      {
        "code": 61557,
        "css": "glyph111",
        "file": "glyph111"
      },
      {
        "code": 61558,
        "css": "glyph112",
        "file": "glyph112"
      },
      {
        "code": 61559,
        "css": "glyph113",
        "file": "glyph113"
      },
      {
        "code": 61560,
        "css": "glyph114",
        "file": "glyph114"
      },
      {
        "code": 61561,
        "css": "glyph115",
        "file": "glyph115"
      },
      {
        "code": 61562,
        "css": "glyph116",
        "file": "glyph116"
      },
      {
        "code": 61563,
        "css": "glyph117",
        "file": "glyph117"
      },
      {
        "code": 61564,
        "css": "glyph118",
        "file": "glyph118"
      },
      {
        "code": 61565,
        "css": "glyph119",
        "file": "glyph119"
      },
      {
        "code": 61566,
        "css": "glyph120",
        "file": "glyph120"
      },
      {
        "code": 61568,
        "css": "glyph121",
        "file": "glyph121"
      },
      {
        "code": 61569,
        "css": "glyph122",
        "file": "glyph122"
      },
      {
        "code": 61570,
        "css": "glyph123",
        "file": "glyph123"
      },
      {
        "code": 61571,
        "css": "glyph124",
        "file": "glyph124"
      },
      {
        "code": 61572,
        "css": "glyph125",
        "file": "glyph125"
      },
      {
        "code": 61573,
        "css": "glyph126",
        "file": "glyph126"
      },
      {
        "code": 61574,
        "css": "glyph127",
        "file": "glyph127"
      },
      {
        "code": 61575,
        "css": "glyph128",
        "file": "glyph128"
      },
      {
        "code": 61576,
        "css": "glyph129",
        "file": "glyph129"
      },
      {
        "code": 61577,
        "css": "glyph130",
        "file": "glyph130"
      },
      {
        "code": 61578,
        "css": "glyph131",
        "file": "glyph131"
      },
      {
        "code": 61579,
        "css": "glyph132",
        "file": "glyph132"
      },
      {
        "code": 61580,
        "css": "glyph133",
        "file": "glyph133"
      },
      {
        "code": 61581,
        "css": "glyph134",
        "file": "glyph134"
      },
      {
        "code": 61582,
        "css": "glyph135",
        "file": "glyph135"
      },
      {
        "code": 61584,
        "css": "glyph136",
        "file": "glyph136"
      },
      {
        "code": 61585,
        "css": "glyph137",
        "file": "glyph137"
      },
      {
        "code": 61586,
        "css": "glyph138",
        "file": "glyph138"
      },
      {
        "code": 61587,
        "css": "glyph139",
        "file": "glyph139"
      },
      {
        "code": 61588,
        "css": "glyph140",
        "file": "glyph140"
      }
    ],
    "font": {
      "fontname": "fontawesome",
      "descent": 410,
      "copyright": "None",
      "familyname": "Font Awesome",
      "weight": "Regular",
      "version": "1.0",
      "fullname": "Font Awesome",
      "ascent": 1638
    },
    "transform": {
      "rescale": 2.0,
      "offset": -0.2
    },
    "id": 1
  },
  {
    "glyphs": [
      {
        "code": 35,
        "css": "hash",
        "file": "hash"
      },
      {
        "code": 63,
        "css": "question_mark",
        "file": "question_mark"
      },
      {
        "code": 64,
        "css": "at",
        "file": "at"
      },
      {
        "code": 182,
        "css": "pilcrow",
        "file": "pilcrow"
      },
      {
        "code": 8505,
        "css": "info",
        "file": "info"
      },
      {
        "code": 8592,
        "css": "arrow_left",
        "file": "arrow_left"
      },
      {
        "code": 8593,
        "css": "arrow_up",
        "file": "arrow_up"
      },
      {
        "code": 8594,
        "css": "arrow_right",
        "file": "arrow_right"
      },
      {
        "code": 8595,
        "css": "arrow_down",
        "file": "arrow_down"
      },
      {
        "code": 8962,
        "css": "home",
        "file": "home"
      },
      {
        "code": 9788,
        "css": "sun_stroke",
        "file": "sun_stroke"
      },
      {
        "code": 9728,
        "css": "sun_fill",
        "file": "sun_fill"
      },
      {
        "code": 9729,
        "css": "cloud",
        "file": "cloud"
      },
      {
        "code": 9730,
        "css": "umbrella",
        "file": "umbrella"
      },
      {
        "code": 9733,
        "css": "star",
        "file": "star"
      },
      {
        "code": 9790,
        "css": "moon_stroke",
        "file": "moon_stroke"
      },
      {
        "code": 57466,
        "css": "moon_fill",
        "file": "moon_fill"
      },
      {
        "code": 9825,
        "css": "heart_stroke",
        "file": "heart_stroke"
      },
      {
        "code": 9829,
        "css": "heart_fill",
        "file": "heart_fill"
      },
      {
        "code": 9881,
        "css": "cog",
        "file": "cog"
      },
      {
        "code": 9889,
        "css": "bolt",
        "file": "bolt"
      },
      {
        "code": 9919,
        "css": "key_stroke",
        "file": "key_stroke"
      },
      {
        "code": 128273,
        "css": "key_fill",
        "file": "key_fill"
      },
      {
        "code": 9926,
        "css": "rain",
        "file": "rain"
      },
      {
        "code": 128683,
        "css": "denied",
        "file": "denied"
      },
      {
        "code": 9993,
        "css": "mail",
        "file": "mail"
      },
      {
        "code": 9998,
        "css": "pen",
        "file": "pen"
      },
      {
        "code": 10003,
        "css": "check",
        "file": "check"
      },
      {
        "code": 10004,
        "css": "check_alt",
        "file": "check_alt"
      },
      {
        "code": 10007,
        "css": "x",
        "file": "x"
      },
      {
        "code": 10008,
        "css": "x_alt",
        "file": "x_alt"
      },
      {
        "code": 10077,
        "css": "left_quote",
        "file": "left_quote"
      },
      {
        "code": 10078,
        "css": "right_quote",
        "file": "right_quote"
      },
      {
        "code": 10133,
        "css": "plus",
        "file": "plus"
      },
      {
        "code": 10134,
        "css": "minus",
        "file": "minus"
      },
      {
        "code": 10549,
        "css": "curved_arrow",
        "file": "curved_arrow"
      },
      {
        "code": 128196,
        "css": "document_alt_stroke",
        "file": "document_alt_stroke"
      },
      {
        "code": 57472,
        "css": "document_alt_fill",
        "file": "document_alt_fill"
      },
      {
        "code": 128197,
        "css": "calendar",
        "file": "calendar"
      },
      {
        "code": 57346,
        "css": "map_pin_alt",
        "file": "map_pin_alt"
      },
      {
        "code": 57347,
        "css": "comment_alt1_stroke",
        "file": "comment_alt1_stroke"
      },
      {
        "code": 57475,
        "css": "comment_alt1_fill",
        "file": "comment_alt1_fill"
      },
      {
        "code": 57348,
        "css": "comment_alt2_stroke",
        "file": "comment_alt2_stroke"
      },
      {
        "code": 57476,
        "css": "comment_alt2_fill",
        "file": "comment_alt2_fill"
      },
      {
        "code": 57349,
        "css": "pen_alt_stroke",
        "file": "pen_alt_stroke"
      },
      {
        "code": 57477,
        "css": "pen_alt_fill",
        "file": "pen_alt_fill"
      },
      {
        "code": 57350,
        "css": "pen_alt2",
        "file": "pen_alt2"
      },
      {
        "code": 57351,
        "css": "chat_alt_stroke",
        "file": "chat_alt_stroke"
      },
      {
        "code": 57479,
        "css": "chat_alt_fill",
        "file": "chat_alt_fill"
      },
      {
        "code": 57352,
        "css": "plus_alt",
        "file": "plus_alt"
      },
      {
        "code": 57353,
        "css": "minus_alt",
        "file": "minus_alt"
      },
      {
        "code": 57354,
        "css": "bars_alt",
        "file": "bars_alt"
      },
      {
        "code": 128212,
        "css": "book_alt",
        "file": "book_alt"
      },
      {
        "code": 57356,
        "css": "aperture_alt",
        "file": "aperture_alt"
      },
      {
        "code": 57360,
        "css": "beaker_alt",
        "file": "beaker_alt"
      },
      {
        "code": 57361,
        "css": "left_quote_alt",
        "file": "left_quote_alt"
      },
      {
        "code": 57362,
        "css": "right_quote_alt",
        "file": "right_quote_alt"
      },
      {
        "code": 57363,
        "css": "arrow_left_alt1",
        "file": "arrow_left_alt1"
      },
      {
        "code": 57364,
        "css": "arrow_up_alt1",
        "file": "arrow_up_alt1"
      },
      {
        "code": 57365,
        "css": "arrow_right_alt1",
        "file": "arrow_right_alt1"
      },
      {
        "code": 57366,
        "css": "arrow_down_alt1",
        "file": "arrow_down_alt1"
      },
      {
        "code": 57367,
        "css": "arrow_left_alt2",
        "file": "arrow_left_alt2"
      },
      {
        "code": 57368,
        "css": "arrow_up_alt2",
        "file": "arrow_up_alt2"
      },
      {
        "code": 57369,
        "css": "arrow_right_alt2",
        "file": "arrow_right_alt2"
      },
      {
        "code": 57370,
        "css": "arrow_down_alt2",
        "file": "arrow_down_alt2"
      },
      {
        "code": 57371,
        "css": "brush",
        "file": "brush"
      },
      {
        "code": 57372,
        "css": "brush_alt",
        "file": "brush_alt"
      },
      {
        "code": 57374,
        "css": "eyedropper",
        "file": "eyedropper"
      },
      {
        "code": 57375,
        "css": "layers",
        "file": "layers"
      },
      {
        "code": 57376,
        "css": "layers_alt",
        "file": "layers_alt"
      },
      {
        "code": 57377,
        "css": "compass",
        "file": "compass"
      },
      {
        "code": 57378,
        "css": "award_stroke",
        "file": "award_stroke"
      },
      {
        "code": 57506,
        "css": "award_fill",
        "file": "award_fill"
      },
      {
        "code": 57379,
        "css": "beaker",
        "file": "beaker"
      },
      {
        "code": 57380,
        "css": "steering_wheel",
        "file": "steering_wheel"
      },
      {
        "code": 57381,
        "css": "eye",
        "file": "eye"
      },
      {
        "code": 57382,
        "css": "aperture",
        "file": "aperture"
      },
      {
        "code": 57383,
        "css": "image",
        "file": "image"
      },
      {
        "code": 57384,
        "css": "chart",
        "file": "chart"
      },
      {
        "code": 57385,
        "css": "chart_alt",
        "file": "chart_alt"
      },
      {
        "code": 127919,
        "css": "target",
        "file": "target"
      },
      {
        "code": 57387,
        "css": "tag_stroke",
        "file": "tag_stroke"
      },
      {
        "code": 57515,
        "css": "tag_fill",
        "file": "tag_fill"
      },
      {
        "code": 57388,
        "css": "rss",
        "file": "rss"
      },
      {
        "code": 57389,
        "css": "rss_alt",
        "file": "rss_alt"
      },
      {
        "code": 57390,
        "css": "share",
        "file": "share"
      },
      {
        "code": 8630,
        "css": "undo",
        "file": "undo"
      },
      {
        "code": 8635,
        "css": "reload",
        "file": "reload"
      },
      {
        "code": 57393,
        "css": "reload_alt",
        "file": "reload_alt"
      },
      {
        "code": 57394,
        "css": "loop_alt1",
        "file": "loop_alt1"
      },
      {
        "code": 57395,
        "css": "loop_alt2",
        "file": "loop_alt2"
      },
      {
        "code": 57396,
        "css": "loop_alt3",
        "file": "loop_alt3"
      },
      {
        "code": 57397,
        "css": "loop_alt4",
        "file": "loop_alt4"
      },
      {
        "code": 57398,
        "css": "spin",
        "file": "spin"
      },
      {
        "code": 57399,
        "css": "spin_alt",
        "file": "spin_alt"
      },
      {
        "code": 57400,
        "css": "move_horizontal",
        "file": "move_horizontal"
      },
      {
        "code": 57401,
        "css": "move_horizontal_alt1",
        "file": "move_horizontal_alt1"
      },
      {
        "code": 57402,
        "css": "move_horizontal_alt2",
        "file": "move_horizontal_alt2"
      },
      {
        "code": 57403,
        "css": "move_vertical",
        "file": "move_vertical"
      },
      {
        "code": 57404,
        "css": "move_vertical_alt1",
        "file": "move_vertical_alt1"
      },
      {
        "code": 57405,
        "css": "move_vertical_alt2",
        "file": "move_vertical_alt2"
      },
      {
        "code": 57406,
        "css": "move",
        "file": "move"
      },
      {
        "code": 57407,
        "css": "move_alt1",
        "file": "move_alt1"
      },
      {
        "code": 57408,
        "css": "move_alt2",
        "file": "move_alt2"
      },
      {
        "code": 57409,
        "css": "transfer",
        "file": "transfer"
      },
      {
        "code": 57410,
        "css": "download",
        "file": "download"
      },
      {
        "code": 57411,
        "css": "upload",
        "file": "upload"
      },
      {
        "code": 57412,
        "css": "cloud_download",
        "file": "cloud_download"
      },
      {
        "code": 57413,
        "css": "cloud_upload",
        "file": "cloud_upload"
      },
      {
        "code": 9095,
        "css": "fork",
        "file": "fork"
      },
      {
        "code": 9659,
        "css": "play",
        "file": "play"
      },
      {
        "code": 57416,
        "css": "play_alt",
        "file": "play_alt"
      },
      {
        "code": 9097,
        "css": "pause",
        "file": "pause"
      },
      {
        "code": 9642,
        "css": "stop",
        "file": "stop"
      },
      {
        "code": 9167,
        "css": "eject",
        "file": "eject"
      },
      {
        "code": 9198,
        "css": "first",
        "file": "first"
      },
      {
        "code": 9197,
        "css": "last",
        "file": "last"
      },
      {
        "code": 57422,
        "css": "fullscreen",
        "file": "fullscreen"
      },
      {
        "code": 57423,
        "css": "fullscreen_alt",
        "file": "fullscreen_alt"
      },
      {
        "code": 57424,
        "css": "fullscreen_exit",
        "file": "fullscreen_exit"
      },
      {
        "code": 57425,
        "css": "fullscreen_exit_alt",
        "file": "fullscreen_exit_alt"
      },
      {
        "code": 57426,
        "css": "equalizer",
        "file": "equalizer"
      },
      {
        "code": 57427,
        "css": "article",
        "file": "article"
      },
      {
        "code": 57428,
        "css": "read_more",
        "file": "read_more"
      },
      {
        "code": 57429,
        "css": "list",
        "file": "list"
      },
      {
        "code": 57430,
        "css": "list_nested",
        "file": "list_nested"
      },
      {
        "code": 57431,
        "css": "cursor",
        "file": "cursor"
      },
      {
        "code": 57432,
        "css": "dial",
        "file": "dial"
      },
      {
        "code": 57433,
        "css": "new_window",
        "file": "new_window"
      },
      {
        "code": 57434,
        "css": "trash_stroke",
        "file": "trash_stroke"
      },
      {
        "code": 57562,
        "css": "trash_fill",
        "file": "trash_fill"
      },
      {
        "code": 57435,
        "css": "battery_half",
        "file": "battery_half"
      },
      {
        "code": 57436,
        "css": "battery_empty",
        "file": "battery_empty"
      },
      {
        "code": 57437,
        "css": "battery_charging",
        "file": "battery_charging"
      },
      {
        "code": 57438,
        "css": "chat",
        "file": "chat"
      },
      {
        "code": 127908,
        "css": "mic",
        "file": "mic"
      },
      {
        "code": 127916,
        "css": "movie",
        "file": "movie"
      },
      {
        "code": 127911,
        "css": "headphones",
        "file": "headphones"
      },
      {
        "code": 128100,
        "css": "user",
        "file": "user"
      },
      {
        "code": 128161,
        "css": "lightbulb",
        "file": "lightbulb"
      },
      {
        "code": 128191,
        "css": "cd",
        "file": "cd"
      },
      {
        "code": 57445,
        "css": "folder_stroke",
        "file": "folder_stroke"
      },
      {
        "code": 57573,
        "css": "folder_fill",
        "file": "folder_fill"
      },
      {
        "code": 128195,
        "css": "document_stroke",
        "file": "document_stroke"
      },
      {
        "code": 57574,
        "css": "document_fill",
        "file": "document_fill"
      },
      {
        "code": 128204,
        "css": "pin",
        "file": "pin"
      },
      {
        "code": 57448,
        "css": "map_pin_stroke",
        "file": "map_pin_stroke"
      },
      {
        "code": 57576,
        "css": "map_pin_fill",
        "file": "map_pin_fill"
      },
      {
        "code": 128213,
        "css": "book",
        "file": "book"
      },
      {
        "code": 128214,
        "css": "book_alt2",
        "file": "book_alt2"
      },
      {
        "code": 57451,
        "css": "box",
        "file": "box"
      },
      {
        "code": 128198,
        "css": "calendar_alt_stroke",
        "file": "calendar_alt_stroke"
      },
      {
        "code": 57580,
        "css": "calendar_alt_fill",
        "file": "calendar_alt_fill"
      },
      {
        "code": 57453,
        "css": "comment_stroke",
        "file": "comment_stroke"
      },
      {
        "code": 57581,
        "css": "comment_fill",
        "file": "comment_fill"
      },
      {
        "code": 57454,
        "css": "iphone",
        "file": "iphone"
      },
      {
        "code": 57455,
        "css": "bars",
        "file": "bars"
      },
      {
        "code": 128247,
        "css": "camera",
        "file": "camera"
      },
      {
        "code": 128263,
        "css": "volume_mute",
        "file": "volume_mute"
      },
      {
        "code": 128266,
        "css": "volume",
        "file": "volume"
      },
      {
        "code": 57459,
        "css": "battery_full",
        "file": "battery_full"
      },
      {
        "code": 128270,
        "css": "magnifying_glass",
        "file": "magnifying_glass"
      },
      {
        "code": 57461,
        "css": "lock_stroke",
        "file": "lock_stroke"
      },
      {
        "code": 128274,
        "css": "lock_fill",
        "file": "lock_fill"
      },
      {
        "code": 57462,
        "css": "unlock_stroke",
        "file": "unlock_stroke"
      },
      {
        "code": 128275,
        "css": "unlock_fill",
        "file": "unlock_fill"
      },
      {
        "code": 128279,
        "css": "link",
        "file": "link"
      },
      {
        "code": 128295,
        "css": "wrench",
        "file": "wrench"
      },
      {
        "code": 128340,
        "css": "clock",
        "file": "clock"
      },
      {
        "code": 57482,
        "css": "paperclip",
        "file": "paperclip"
      }
    ],
    "font": {
      "fontname": "iconic",
      "descent": 410,
      "copyright": "Copyright (C) 2012 by Daniel Bruce",
      "familyname": "Iconic",
      "weight": "Medium",
      "version": "1.0",
      "fullname": "Iconic",
      "ascent": 1638
    },
    "transform": {
      "rescale": 1.3,
      "offset": -0.05
    },
    "id": 2
  },
  {
    "glyphs": [
      {
        "code": 35,
        "css": "glyph5",
        "file": "glyph5"
      },
      {
        "code": 37,
        "css": "glyph6",
        "file": "glyph6"
      },
      {
        "code": 57345,
        "from": 38,
        "css": "glyph7",
        "file": "glyph7"
      },
      {
        "code": 57346,
        "from": 39,
        "css": "glyph8",
        "file": "glyph8"
      },
      {
        "code": 40,
        "css": "glyph9",
        "file": "glyph9"
      },
      {
        "code": 41,
        "css": "glyph10",
        "file": "glyph10"
      },
      {
        "code": 42,
        "css": "glyph11",
        "file": "glyph11"
      },
      {
        "code": 43,
        "css": "glyph12",
        "file": "glyph12"
      },
      {
        "code": 44,
        "css": "glyph13",
        "file": "glyph13"
      },
      {
        "code": 45,
        "css": "glyph14",
        "file": "glyph14"
      },
      {
        "code": 46,
        "css": "glyph15",
        "file": "glyph15"
      },
      {
        "code": 47,
        "css": "glyph16",
        "file": "glyph16"
      },
      {
        "code": 48,
        "css": "glyph17",
        "file": "glyph17"
      },
      {
        "code": 49,
        "css": "glyph18",
        "file": "glyph18"
      },
      {
        "code": 50,
        "css": "glyph19",
        "file": "glyph19"
      },
      {
        "code": 51,
        "css": "glyph20",
        "file": "glyph20"
      },
      {
        "code": 52,
        "css": "glyph21",
        "file": "glyph21"
      },
      {
        "code": 53,
        "css": "glyph22",
        "file": "glyph22"
      },
      {
        "code": 54,
        "css": "glyph23",
        "file": "glyph23"
      },
      {
        "code": 55,
        "css": "glyph24",
        "file": "glyph24"
      },
      {
        "code": 58,
        "css": "glyph25",
        "file": "glyph25"
      },
      {
        "code": 59,
        "css": "glyph26",
        "file": "glyph26"
      },
      {
        "code": 57347,
        "from": 60,
        "css": "glyph27",
        "file": "glyph27"
      },
      {
        "code": 57348,
        "from": 62,
        "css": "glyph28",
        "file": "glyph28"
      },
      {
        "code": 63,
        "css": "glyph29",
        "file": "glyph29"
      },
      {
        "code": 64,
        "css": "glyph30",
        "file": "glyph30"
      },
      {
        "code": 65,
        "css": "glyph31",
        "file": "glyph31"
      },
      {
        "code": 66,
        "css": "glyph32",
        "file": "glyph32"
      },
      {
        "code": 67,
        "css": "glyph33",
        "file": "glyph33"
      },
      {
        "code": 68,
        "css": "glyph34",
        "file": "glyph34"
      },
      {
        "code": 70,
        "css": "glyph35",
        "file": "glyph35"
      },
      {
        "code": 72,
        "css": "glyph36",
        "file": "glyph36"
      },
      {
        "code": 73,
        "css": "glyph37",
        "file": "glyph37"
      },
      {
        "code": 74,
        "css": "glyph38",
        "file": "glyph38"
      },
      {
        "code": 75,
        "css": "glyph39",
        "file": "glyph39"
      },
      {
        "code": 76,
        "css": "glyph40",
        "file": "glyph40"
      },
      {
        "code": 77,
        "css": "glyph41",
        "file": "glyph41"
      },
      {
        "code": 78,
        "css": "glyph42",
        "file": "glyph42"
      },
      {
        "code": 79,
        "css": "glyph43",
        "file": "glyph43"
      },
      {
        "code": 80,
        "css": "glyph44",
        "file": "glyph44"
      },
      {
        "code": 81,
        "css": "glyph45",
        "file": "glyph45"
      },
      {
        "code": 82,
        "css": "glyph46",
        "file": "glyph46"
      },
      {
        "code": 83,
        "css": "glyph47",
        "file": "glyph47"
      },
      {
        "code": 84,
        "css": "glyph48",
        "file": "glyph48"
      },
      {
        "code": 85,
        "css": "glyph49",
        "file": "glyph49"
      },
      {
        "code": 86,
        "css": "glyph50",
        "file": "glyph50"
      },
      {
        "code": 87,
        "css": "glyph51",
        "file": "glyph51"
      },
      {
        "code": 88,
        "css": "glyph52",
        "file": "glyph52"
      },
      {
        "code": 90,
        "css": "glyph53",
        "file": "glyph53"
      },
      {
        "code": 91,
        "css": "glyph54",
        "file": "glyph54"
      },
      {
        "code": 57349,
        "from": 92,
        "css": "glyph55",
        "file": "glyph55"
      },
      {
        "code": 93,
        "css": "glyph56",
        "file": "glyph56"
      },
      {
        "code": 95,
        "css": "glyph57",
        "file": "glyph57"
      },
      {
        "code": 96,
        "css": "glyph58",
        "file": "glyph58"
      },
      {
        "code": 97,
        "css": "glyph59",
        "file": "glyph59"
      },
      {
        "code": 98,
        "css": "glyph60",
        "file": "glyph60"
      },
      {
        "code": 99,
        "css": "glyph61",
        "file": "glyph61"
      },
      {
        "code": 100,
        "css": "glyph62",
        "file": "glyph62"
      },
      {
        "code": 101,
        "css": "glyph63",
        "file": "glyph63"
      },
      {
        "code": 102,
        "css": "glyph64",
        "file": "glyph64"
      },
      {
        "code": 103,
        "css": "glyph65",
        "file": "glyph65"
      },
      {
        "code": 104,
        "css": "glyph66",
        "file": "glyph66"
      },
      {
        "code": 105,
        "css": "glyph67",
        "file": "glyph67"
      },
      {
        "code": 106,
        "css": "glyph68",
        "file": "glyph68"
      },
      {
        "code": 107,
        "css": "glyph69",
        "file": "glyph69"
      },
      {
        "code": 108,
        "css": "glyph70",
        "file": "glyph70"
      },
      {
        "code": 109,
        "css": "glyph71",
        "file": "glyph71"
      },
      {
        "code": 110,
        "css": "glyph72",
        "file": "glyph72"
      },
      {
        "code": 111,
        "css": "glyph73",
        "file": "glyph73"
      },
      {
        "code": 112,
        "css": "glyph74",
        "file": "glyph74"
      },
      {
        "code": 113,
        "css": "glyph75",
        "file": "glyph75"
      },
      {
        "code": 114,
        "css": "glyph76",
        "file": "glyph76"
      },
      {
        "code": 115,
        "css": "glyph77",
        "file": "glyph77"
      },
      {
        "code": 116,
        "css": "glyph78",
        "file": "glyph78"
      },
      {
        "code": 117,
        "css": "glyph79",
        "file": "glyph79"
      },
      {
        "code": 118,
        "css": "glyph80",
        "file": "glyph80"
      },
      {
        "code": 119,
        "css": "glyph81",
        "file": "glyph81"
      },
      {
        "code": 120,
        "css": "glyph82",
        "file": "glyph82"
      },
      {
        "code": 121,
        "css": "glyph83",
        "file": "glyph83"
      },
      {
        "code": 122,
        "css": "glyph84",
        "file": "glyph84"
      },
      {
        "code": 123,
        "css": "glyph85",
        "file": "glyph85"
      },
      {
        "code": 125,
        "css": "glyph86",
        "file": "glyph86"
      },
      {
        "code": 126,
        "css": "glyph87",
        "file": "glyph87"
      },
      {
        "code": 178,
        "css": "glyph88",
        "file": "glyph88"
      },
      {
        "code": 179,
        "css": "glyph89",
        "file": "glyph89"
      },
      {
        "code": 185,
        "css": "glyph90",
        "file": "glyph90"
      },
      {
        "code": 215,
        "css": "glyph91",
        "file": "glyph91"
      },
      {
        "code": 57344,
        "css": "glyph92",
        "file": "glyph92"
      }
    ],
    "font": {
      "fontname": "websymbols-regular",
      "descent": 410,
      "copyright": "Copyright (c) 2011 by Just Be Nice studio. All rights reserved.",
      "familyname": "Web Symbols",
      "weight": "Book",
      "version": "1.0",
      "fullname": "Web Symbols Regular",
      "ascent": 1638
    },
    "transform": {
      "rescale": 1.8,
      "offset": 0
    },
    "id": 3
  }
];