// THIS IS AUTOGENERATED FILE. DO NOT EDIT
module.exports = [
  {
    "glyphs": [
      {
        "search": [
          "music",
          "note",
          "song"
        ],
        "code": 9834,
        "file": "music",
        "css": "music"
      },
      {
        "search": [
          "song",
          "music",
          "sound"
        ],
        "code": 127925,
        "file": "song",
        "css": "music-alt"
      },
      {
        "search": [
          "search",
          "find"
        ],
        "code": 128269,
        "file": "classic-search",
        "css": "search"
      },
      {
        "search": [
          "search",
          "find"
        ],
        "code": 128270,
        "file": "search",
        "css": "search-alt"
      },
      {
        "search": [
          "mail",
          "email"
        ],
        "code": 9993,
        "file": "email",
        "css": "mail"
      },
      {
        "search": [
          "heart"
        ],
        "code": 9829,
        "file": "heart",
        "css": "heart"
      },
      {
        "search": [
          "heart"
        ],
        "code": 9825,
        "file": "heart-outlined",
        "css": "heart-empty"
      },
      {
        "search": [
          "star"
        ],
        "code": 9733,
        "file": "star",
        "css": "star"
      },
      {
        "search": [
          "star"
        ],
        "code": 9734,
        "file": "star-outlined",
        "css": "star-empty"
      },
      {
        "search": [
          "profile",
          "contact",
          "user"
        ],
        "code": 128100,
        "file": "contact-user",
        "css": "user"
      },
      {
        "search": [
          "users",
          "contacts",
          "friends"
        ],
        "code": 128101,
        "file": "contacts-users",
        "css": "users"
      },
      {
        "search": [
          "profile",
          "contact",
          "user",
          "add"
        ],
        "code": 59136,
        "file": "add-contact-add-user",
        "css": "user-add"
      },
      {
        "search": [
          "movie",
          "video",
          "film"
        ],
        "code": 127916,
        "file": "movie",
        "css": "video"
      },
      {
        "search": [
          "image",
          "picture",
          "photo"
        ],
        "code": 127748,
        "file": "image",
        "css": "picture"
      },
      {
        "search": [
          "camera",
          "photo"
        ],
        "code": 128247,
        "file": "camera",
        "css": "camera"
      },
      {
        "search": [
          "image",
          "list",
          "thumbnails"
        ],
        "code": 9871,
        "file": "image-list",
        "css": "th"
      },
      {
        "search": [
          "list"
        ],
        "code": 9776,
        "file": "list",
        "css": "th-list"
      },
      {
        "search": [
          "ok",
          true,
          "check",
          "mark"
        ],
        "code": 10003,
        "file": "check-ok",
        "css": "ok"
      },
      {
        "search": [
          "close",
          "cancel",
          "reject"
        ],
        "code": 10005,
        "file": "check-not-ok",
        "css": "cancel"
      },
      {
        "search": [
          "close",
          "cancel",
          "reject"
        ],
        "code": 10006,
        "file": "close-circle",
        "css": "cancel-circle"
      },
      {
        "search": [
          "plus"
        ],
        "code": 43,
        "file": "plus",
        "css": "plus"
      },
      {
        "search": [
          "plus"
        ],
        "code": 10133,
        "file": "plus-circle",
        "css": "plus-circle"
      },
      {
        "search": [
          "minus"
        ],
        "code": 45,
        "file": "minus",
        "css": "minus"
      },
      {
        "search": [
          "minus"
        ],
        "code": 10134,
        "file": "minus-circle",
        "css": "minus-circle"
      },
      {
        "search": [
          "help",
          "question"
        ],
        "code": 10067,
        "file": "help",
        "css": "help"
      },
      {
        "search": [
          "help",
          "question"
        ],
        "code": 59140,
        "file": "help-circle",
        "css": "help-circle"
      },
      {
        "search": [
          "info"
        ],
        "code": 8505,
        "file": "info",
        "css": "info"
      },
      {
        "search": [
          "info"
        ],
        "code": 59141,
        "file": "info-circle",
        "css": "info-circle"
      },
      {
        "search": [
          "back",
          "return"
        ],
        "code": 59142,
        "file": "back",
        "css": "back"
      },
      {
        "search": [
          "back",
          "return"
        ],
        "code": 59143,
        "file": "back-alt",
        "css": "back-alt"
      },
      {
        "search": [
          "home"
        ],
        "code": 8962,
        "file": "home",
        "css": "home"
      },
      {
        "search": [
          "link",
          "url"
        ],
        "code": 128279,
        "file": "link",
        "css": "link"
      },
      {
        "search": [
          "attach",
          "clip"
        ],
        "code": 128206,
        "file": "attach",
        "css": "attach"
      },
      {
        "search": [
          "lock"
        ],
        "code": 128274,
        "file": "lock",
        "css": "lock"
      },
      {
        "search": [
          "lock",
          "unlock"
        ],
        "code": 128275,
        "file": "unlocked",
        "css": "lock-open"
      },
      {
        "search": [
          "eye",
          "subscribe"
        ],
        "code": 59146,
        "file": "view-eye",
        "css": "eye"
      },
      {
        "search": [
          "tag",
          "price",
          "offer"
        ],
        "code": 59148,
        "file": "offer-price-tag",
        "css": "tag"
      },
      {
        "search": [
          "bookmark"
        ],
        "code": 128278,
        "file": "bookmark",
        "css": "bookmark"
      },
      {
        "search": [
          "flag"
        ],
        "code": 9873,
        "file": "flag",
        "css": "flag"
      },
      {
        "search": [
          "thumbs",
          "up",
          "like",
          "vote"
        ],
        "code": 128077,
        "file": "like-thumbs-up",
        "css": "thumbs-up"
      },
      {
        "search": [
          "download"
        ],
        "code": 128229,
        "file": "download",
        "css": "download"
      },
      {
        "search": [
          "upload"
        ],
        "code": 128228,
        "file": "upload",
        "css": "upload"
      },
      {
        "search": [
          "upload",
          "cloud"
        ],
        "code": 59153,
        "file": "upload-to-cloud",
        "css": "upload-cloud"
      },
      {
        "search": [
          "reply"
        ],
        "code": 59154,
        "file": "reply",
        "css": "reply"
      },
      {
        "search": [
          "reply"
        ],
        "code": 59155,
        "file": "reply-to-all",
        "css": "reply-all"
      },
      {
        "search": [
          "forward"
        ],
        "code": 10150,
        "file": "forward",
        "css": "forward"
      },
      {
        "search": [
          "quote"
        ],
        "code": 10078,
        "file": "quote",
        "css": "quote-right"
      },
      {
        "search": [
          "code"
        ],
        "code": 59156,
        "file": "code",
        "css": "code"
      },
      {
        "search": [
          "export",
          "share"
        ],
        "code": 59157,
        "file": "export",
        "css": "export"
      },
      {
        "search": [
          "pencil",
          "write",
          "reply",
          "edit"
        ],
        "code": 9998,
        "file": "write-new",
        "css": "pencil"
      },
      {
        "search": [
          "pen",
          "write",
          "reply",
          "edit",
          "feather"
        ],
        "code": 10002,
        "file": "feather",
        "css": "feather"
      },
      {
        "search": [
          "print"
        ],
        "code": 59158,
        "file": "print",
        "css": "print"
      },
      {
        "search": [
          "retweet",
          "twitter"
        ],
        "code": 59159,
        "file": "retweet",
        "css": "retweet"
      },
      {
        "search": [
          "keyboard"
        ],
        "code": 9000,
        "file": "keyboard",
        "css": "keyboard"
      },
      {
        "search": [
          "comment",
          "reply",
          "write"
        ],
        "code": 59160,
        "file": "comment",
        "css": "comment"
      },
      {
        "search": [
          "chat",
          "talk"
        ],
        "code": 59168,
        "file": "chat",
        "css": "chat"
      },
      {
        "search": [
          "alert",
          "bell",
          "jingle"
        ],
        "code": 128276,
        "file": "alert",
        "css": "bell"
      },
      {
        "search": [
          "attention",
          "warning",
          "alert"
        ],
        "code": 9888,
        "file": "warning",
        "css": "attention"
      },
      {
        "search": [
          "contact",
          "card",
          "vcard"
        ],
        "code": 59170,
        "file": "contact-card",
        "css": "vcard"
      },
      {
        "search": [
          "address"
        ],
        "code": 59171,
        "file": "address",
        "css": "address"
      },
      {
        "search": [
          "location",
          "mark",
          "marker"
        ],
        "code": 59172,
        "file": "location",
        "css": "location"
      },
      {
        "search": [
          "down"
        ],
        "code": 59175,
        "file": "map",
        "css": "map"
      },
      {
        "search": [
          "direction"
        ],
        "code": 10146,
        "file": "direction",
        "css": "direction"
      },
      {
        "search": [
          "compass"
        ],
        "code": 59176,
        "file": "compass",
        "css": "compass"
      },
      {
        "search": [
          "trash",
          "delete"
        ],
        "code": 59177,
        "file": "trash",
        "css": "trash"
      },
      {
        "search": [
          "doc",
          "article"
        ],
        "code": 59184,
        "file": "document",
        "css": "doc"
      },
      {
        "search": [
          "doc",
          "article"
        ],
        "code": 59190,
        "file": "documents",
        "css": "docs"
      },
      {
        "search": [
          "doc",
          "article"
        ],
        "code": 59191,
        "file": "landscape-documents",
        "css": "docs-landscape"
      },
      {
        "search": [
          "doc",
          "text",
          "article"
        ],
        "code": 128196,
        "file": "text-document",
        "css": "doc-text"
      },
      {
        "search": [
          "book",
          "doc"
        ],
        "code": 128214,
        "file": "book",
        "css": "book-open"
      },
      {
        "search": [
          "folder"
        ],
        "code": 128193,
        "file": "folder",
        "css": "folder"
      },
      {
        "search": [
          "archive"
        ],
        "code": 59192,
        "file": "archive",
        "css": "archive"
      },
      {
        "search": [
          "rss"
        ],
        "code": 59194,
        "file": "rss",
        "css": "rss"
      },
      {
        "search": [
          "phone",
          "telephone",
          "call"
        ],
        "code": 128222,
        "file": "phone",
        "css": "phone"
      },
      {
        "search": [
          "settings",
          "cog",
          "gear"
        ],
        "code": 9881,
        "file": "settings",
        "css": "cog"
      },
      {
        "search": [
          "share"
        ],
        "code": 59196,
        "file": "share",
        "css": "share"
      },
      {
        "search": [
          "basket",
          "shopping",
          "cart"
        ],
        "code": 59197,
        "file": "shopping-bag",
        "css": "basket"
      },
      {
        "search": [
          "calendar",
          "date"
        ],
        "code": 128197,
        "file": "calendar",
        "css": "calendar"
      },
      {
        "search": [
          "mic"
        ],
        "code": 127908,
        "file": "mic",
        "css": "mic"
      },
      {
        "search": [
          "volume",
          "sound",
          "mute"
        ],
        "code": 128263,
        "file": "mute",
        "css": "volume-off"
      },
      {
        "search": [
          "volume",
          "sound"
        ],
        "code": 128266,
        "file": "sound",
        "css": "volume-up"
      },
      {
        "search": [
          "volume",
          "sound"
        ],
        "code": 59202,
        "file": "volume",
        "css": "volume"
      },
      {
        "search": [
          "clock",
          "time"
        ],
        "code": 128340,
        "file": "time-clock",
        "css": "clock"
      },
      {
        "search": [
          "clock",
          "hourglass",
          "busy",
          "wait"
        ],
        "code": 9203,
        "file": "time-glass",
        "css": "hourglass"
      },
      {
        "search": [
          "idea",
          "lamp",
          "light"
        ],
        "code": 128161,
        "file": "light-bulb",
        "css": "lamp"
      },
      {
        "search": [
          "light",
          "dim",
          "bright"
        ],
        "code": 128261,
        "file": "light-down",
        "css": "light-down"
      },
      {
        "search": [
          "light",
          "dim",
          "bright"
        ],
        "code": 128262,
        "file": "light-up",
        "css": "light-up"
      },
      {
        "search": [
          "block",
          "deny"
        ],
        "code": 128683,
        "file": "block",
        "css": "block"
      },
      {
        "search": [
          "resize",
          "fullscreen"
        ],
        "code": 59204,
        "file": "full-screen",
        "css": "resize-full"
      },
      {
        "search": [
          "resize"
        ],
        "code": 59206,
        "file": "small-screen",
        "css": "resize-small"
      },
      {
        "search": [
          "popup",
          "window"
        ],
        "code": 59212,
        "file": "popup",
        "css": "popup"
      },
      {
        "search": [
          "publish"
        ],
        "code": 59213,
        "file": "publish",
        "css": "publish"
      },
      {
        "search": [
          "window"
        ],
        "code": 59214,
        "file": "browser",
        "css": "window"
      },
      {
        "search": [
          "arrow",
          "dropdown",
          "combobox"
        ],
        "code": 59215,
        "file": "select-box-arrow",
        "css": "arrow-combo"
      },
      {
        "search": [
          "arrow",
          "down",
          "download"
        ],
        "code": 59224,
        "file": "down-circle-arrow",
        "css": "down-circle2"
      },
      {
        "search": [
          "arrow",
          "left"
        ],
        "code": 59225,
        "file": "left-circle-arrow",
        "css": "left-circle2"
      },
      {
        "search": [
          "arrow",
          "right"
        ],
        "code": 59226,
        "file": "right-circle-arrow",
        "css": "right-circle2"
      },
      {
        "search": [
          "arrow",
          "up",
          "upload"
        ],
        "code": 59227,
        "file": "up-circle-arrow",
        "css": "up-circle2"
      },
      {
        "search": [
          "arrow",
          "down"
        ],
        "code": 59228,
        "file": "open-arrow-down",
        "css": "down-open"
      },
      {
        "search": [
          "arrow",
          "left"
        ],
        "code": 59229,
        "file": "open-arrow-left",
        "css": "left-open"
      },
      {
        "search": [
          "arrow",
          "right"
        ],
        "code": 59230,
        "file": "open-arrow-right",
        "css": "right-open"
      },
      {
        "search": [
          "arrow",
          "up"
        ],
        "code": 59231,
        "file": "open-arrow-up",
        "css": "up-open"
      },
      {
        "search": [
          "arrow",
          "down"
        ],
        "code": 11015,
        "file": "thin-arrow-down",
        "css": "down-thin"
      },
      {
        "search": [
          "arrow",
          "left"
        ],
        "code": 11013,
        "file": "thin-arrow-left",
        "css": "left-thin"
      },
      {
        "search": [
          "arrow",
          "right"
        ],
        "code": 10145,
        "file": "thin-arrow-right",
        "css": "right-thin"
      },
      {
        "search": [
          "arrow",
          "up"
        ],
        "code": 11014,
        "file": "thin-arrow-up",
        "css": "up-thin"
      },
      {
        "search": [
          "arrow",
          "down"
        ],
        "code": 9662,
        "file": "direction-arrow-down",
        "css": "down-dir"
      },
      {
        "search": [
          "arrow",
          "left"
        ],
        "code": 9666,
        "file": "direction-arrow-left",
        "css": "left-dir"
      },
      {
        "search": [
          "arrow",
          "right"
        ],
        "code": 9656,
        "file": "direction-arrow-right",
        "css": "right-dir"
      },
      {
        "search": [
          "arrow",
          "up"
        ],
        "code": 9652,
        "file": "direction-arrow-up",
        "css": "up-dir"
      },
      {
        "search": [
          "arrow",
          "down"
        ],
        "code": 58544,
        "file": "bold-down-arrow",
        "css": "down-bold"
      },
      {
        "search": [
          "arrow",
          "left"
        ],
        "code": 58541,
        "file": "bold-left-arrow",
        "css": "left-bold"
      },
      {
        "search": [
          "arrow",
          "right"
        ],
        "code": 58542,
        "file": "bold-right-arrow",
        "css": "right-bold"
      },
      {
        "search": [
          "arrow",
          "up"
        ],
        "code": 58543,
        "file": "bold-up-arrow",
        "css": "up-bold"
      },
      {
        "search": [
          "arrow",
          "down"
        ],
        "code": 8595,
        "file": "down-arrow",
        "css": "down"
      },
      {
        "search": [
          "arrow",
          "left"
        ],
        "code": 8592,
        "file": "left-arrow",
        "css": "left"
      },
      {
        "search": [
          "arrow",
          "right"
        ],
        "code": 8594,
        "file": "right-arrow",
        "css": "right"
      },
      {
        "search": [
          "arrow",
          "up"
        ],
        "code": 8593,
        "file": "up-arrow",
        "css": "up"
      },
      {
        "search": [
          "reload",
          "undo"
        ],
        "code": 10226,
        "file": "reload-CCW",
        "css": "ccw"
      },
      {
        "search": [
          "reload",
          "redo",
          "repeat"
        ],
        "code": 10227,
        "file": "reload-CW",
        "css": "cw"
      },
      {
        "search": [
          "down"
        ],
        "code": 8627,
        "file": "level-down",
        "css": "level-down"
      },
      {
        "search": [
          "shuffle",
          "random"
        ],
        "code": 128256,
        "file": "shuffle",
        "css": "shuffle"
      },
      {
        "search": [
          "play",
          "player"
        ],
        "code": 9654,
        "file": "play",
        "css": "play"
      },
      {
        "search": [
          "stop",
          "player"
        ],
        "code": 9642,
        "file": "stop",
        "css": "stop"
      },
      {
        "search": [
          "pause",
          "player"
        ],
        "code": 9097,
        "file": "paus",
        "css": "pause"
      },
      {
        "search": [
          "record",
          "player"
        ],
        "code": 9899,
        "file": "record",
        "css": "record"
      },
      {
        "search": [
          "right",
          "player"
        ],
        "code": 9197,
        "file": "jump-to-end",
        "css": "to-end"
      },
      {
        "search": [
          "left",
          "player"
        ],
        "code": 9198,
        "file": "jump-to-start",
        "css": "to-start"
      },
      {
        "search": [
          "right",
          "player"
        ],
        "code": 9193,
        "file": "fast-forward",
        "css": "fast-fw"
      },
      {
        "search": [
          "left",
          "player"
        ],
        "code": 9194,
        "file": "fast-backward",
        "css": "fast-bw"
      },
      {
        "search": [
          "progress",
          "charge"
        ],
        "code": 59240,
        "file": "charge-empty",
        "css": "progress-0"
      },
      {
        "search": [
          "progress",
          "charge"
        ],
        "code": 59241,
        "file": "charge-one-third",
        "css": "progress-1"
      },
      {
        "search": [
          "progress",
          "charge"
        ],
        "code": 59242,
        "file": "charge-two-thirds",
        "css": "progress-2"
      },
      {
        "search": [
          "progress",
          "charge"
        ],
        "code": 59243,
        "file": "charge-full",
        "css": "progress-3"
      },
      {
        "search": [
          "target"
        ],
        "code": 127919,
        "file": "center-crosshair",
        "css": "target"
      },
      {
        "search": [
          "palette"
        ],
        "code": 127912,
        "file": "palette",
        "css": "palette"
      },
      {
        "search": [
          "add",
          "list"
        ],
        "code": 57347,
        "file": "add-to-list",
        "css": "list-add"
      },
      {
        "search": [
          "broadcast",
          "wifi",
          "signal"
        ],
        "code": 59248,
        "file": "broadcast",
        "css": "signal"
      },
      {
        "search": [
          "top",
          "trophy"
        ],
        "code": 127942,
        "file": "top-list",
        "css": "top-list"
      },
      {
        "search": [
          "battery"
        ],
        "code": 128267,
        "file": "battery",
        "css": "battery"
      },
      {
        "search": [
          "back",
          "time"
        ],
        "code": 59249,
        "file": "back-in-time",
        "css": "back-in-time"
      },
      {
        "search": [
          "tv",
          "screen",
          "monitor"
        ],
        "code": 128187,
        "file": "tv-screen",
        "css": "monitor"
      },
      {
        "search": [
          "mobile",
          "iphone"
        ],
        "code": 128241,
        "file": "mobile",
        "css": "mobile"
      },
      {
        "search": [
          "net"
        ],
        "code": 59254,
        "file": "network",
        "css": "net"
      },
      {
        "search": [
          "cd",
          "vinyl"
        ],
        "code": 128191,
        "file": "vinyl-record",
        "css": "cd"
      },
      {
        "search": [
          "inbox"
        ],
        "code": 59255,
        "file": "inbox",
        "css": "inbox"
      },
      {
        "search": [
          "install"
        ],
        "code": 59256,
        "file": "install",
        "css": "install"
      },
      {
        "search": [
          "globe"
        ],
        "code": 119565,
        "file": "globe",
        "css": "globe"
      },
      {
        "search": [
          "cloud"
        ],
        "code": 9729,
        "file": "cloud",
        "css": "cloud"
      },
      {
        "search": [
          "flash",
          "bolt"
        ],
        "code": 9889,
        "file": "flash",
        "css": "flash"
      },
      {
        "search": [
          "moon",
          "sleep"
        ],
        "code": 9789,
        "file": "sleep",
        "css": "moon"
      },
      {
        "search": [
          "flight",
          "plane",
          "airplane"
        ],
        "code": 9992,
        "file": "flight",
        "css": "flight"
      },
      {
        "search": [
          "leaf"
        ],
        "code": 127810,
        "file": "leaf",
        "css": "leaf"
      },
      {
        "search": [
          "lifebuoy"
        ],
        "code": 59272,
        "file": "lifebuoy",
        "css": "lifebuoy"
      },
      {
        "search": [
          "mouse",
          "website"
        ],
        "code": 59273,
        "file": "mouse-website",
        "css": "mouse"
      },
      {
        "search": [
          "bag"
        ],
        "code": 59274,
        "file": "suitecase",
        "css": "bag"
      },
      {
        "search": [
          "dot"
        ],
        "code": 59275,
        "file": "dot",
        "css": "dot"
      },
      {
        "search": [
          "dot",
          "flickr"
        ],
        "code": 59276,
        "file": "dots-two",
        "css": "dot-2"
      },
      {
        "search": [
          "dot"
        ],
        "code": 59277,
        "file": "dots-three",
        "css": "dot-3"
      },
      {
        "search": [
          "google",
          "circles"
        ],
        "code": 62224,
        "file": "google-circles",
        "css": "google-circles"
      },
      {
        "search": [
          "creative",
          "commons"
        ],
        "code": 59301,
        "file": "creative-commons",
        "css": "cc"
      },
      {
        "search": [
          "entypo"
        ],
        "code": 62976,
        "file": "entypo-square",
        "css": "logo-entypo"
      },
      {
        "search": [
          "sweden"
        ],
        "code": 62977,
        "file": "sweden",
        "css": "flag-sw"
      },
      {
        "search": [
          "daniel",
          "bruce"
        ],
        "code": 62979,
        "file": "db-signature",
        "css": "logo-db"
      }
    ],
    "font": {
      "fontname": "entypo",
      "descent": 200,
      "copyright": "Copyright (C) 2012 by Daniel Bruce",
      "familyname": "Entypo",
      "weight": "Medium",
      "version": "1.0",
      "fullname": "Entypo",
      "ascent": 800
    },
    "meta": {
      "github": "https://github.com/danielbruce/entypo",
      "licence_url": "http://scripts.sil.org/OFL",
      "licence": "SIL",
      "author": "Daniel Buce",
      "twitter": "http://twitter.com/danielbruce_",
      "email": "daniel@precinct.net",
      "css_prefix": "icon-",
      "homepage": "http://www.entypo.com",
      "dribble": "http://dribbble.com/danielbruce",
      "columns": 4
    },
    "id": 0
  },
  {
    "font": {
      "fontname": "fontawesome",
      "descent": 200,
      "copyright": "Copyright (C) 2012 by Dave Gandy",
      "familyname": "Font Awesome",
      "weight": "Regular",
      "version": "1.0",
      "fullname": "Font Awesome",
      "ascent": 800
    },
    "meta": {
      "github": "https://github.com/FortAwesome/Font-Awesome",
      "licence_url": "http://creativecommons.org/licenses/by/3.0/",
      "licence": "CC BY 3.0",
      "author": "Dave Gandy",
      "twitter": "http://twitter.com/fortaweso_me/",
      "css_prefix": "icon-",
      "homepage": "http://fortawesome.github.com/Font-Awesome/",
      "email": "dave@davegandy.com",
      "columns": 4
    },
    "glyphs": [
      {
        "search": [
          "glass"
        ],
        "code": 127864,
        "from": 61440,
        "css": "glass"
      },
      {
        "search": [
          "music",
          "note",
          "song",
          "sound"
        ],
        "code": 9835,
        "from": 61441,
        "css": "music"
      },
      {
        "search": [
          "search",
          "find"
        ],
        "code": 128269,
        "from": 61442,
        "css": "search"
      },
      {
        "search": [
          "mail",
          "email"
        ],
        "code": 9993,
        "from": 61443,
        "css": "mail"
      },
      {
        "search": [
          "heart"
        ],
        "code": 9829,
        "from": 61444,
        "css": "heart"
      },
      {
        "search": [
          "heart"
        ],
        "code": 9825,
        "from": 61578,
        "css": "heart-empty"
      },
      {
        "search": [
          "star"
        ],
        "code": 9733,
        "from": 61445,
        "css": "star"
      },
      {
        "search": [
          "star"
        ],
        "code": 9734,
        "from": 61446,
        "css": "star-empty"
      },
      {
        "search": [
          "star"
        ],
        "code": 59137,
        "from": 61577,
        "css": "star-half"
      },
      {
        "search": [
          "profile",
          "contact",
          "user"
        ],
        "code": 128100,
        "from": 61447,
        "css": "user"
      },
      {
        "search": [
          "movie",
          "video",
          "film"
        ],
        "code": 127916,
        "from": 61448,
        "css": "video"
      },
      {
        "search": [
          "facetime",
          "movie",
          "video",
          "film"
        ],
        "code": 127909,
        "from": 61501,
        "css": "videocam"
      },
      {
        "search": [
          "camera",
          "photo"
        ],
        "code": 128247,
        "from": 61488,
        "css": "camera"
      },
      {
        "search": [
          "camera",
          "photo"
        ],
        "code": 59151,
        "from": 61571,
        "css": "camera-alt"
      },
      {
        "search": [
          "image",
          "picture",
          "photo"
        ],
        "code": 127748,
        "from": 61502,
        "css": "picture"
      },
      {
        "search": [
          "image",
          "list",
          "thumbnails"
        ],
        "code": 59144,
        "from": 61449,
        "css": "th-large"
      },
      {
        "search": [
          "image",
          "list",
          "thumbnails"
        ],
        "code": 9871,
        "from": 61450,
        "css": "th"
      },
      {
        "search": [
          "list"
        ],
        "code": 9776,
        "from": 61451,
        "css": "list"
      },
      {
        "search": [
          "ok",
          true,
          "check",
          "mark"
        ],
        "code": 10003,
        "from": 61452,
        "css": "ok"
      },
      {
        "search": [
          "ok",
          true,
          "check",
          "mark"
        ],
        "code": 10004,
        "from": 61528,
        "css": "ok-circle"
      },
      {
        "search": [
          "ok",
          true,
          "check",
          "mark"
        ],
        "code": 59138,
        "from": 61533,
        "css": "ok-circle2"
      },
      {
        "search": [
          "close",
          "cancel",
          "reject"
        ],
        "code": 10005,
        "from": 61453,
        "css": "cancel"
      },
      {
        "search": [
          "close",
          "cancel",
          "reject"
        ],
        "code": 10006,
        "from": 61527,
        "css": "cancel-circle"
      },
      {
        "search": [
          "close",
          "cancel",
          "reject"
        ],
        "code": 59139,
        "from": 61532,
        "css": "cancel-circle2"
      },
      {
        "search": [
          "plus"
        ],
        "code": 43,
        "from": 61543,
        "css": "plus"
      },
      {
        "search": [
          "plus"
        ],
        "code": 10133,
        "from": 61525,
        "css": "plus-circle"
      },
      {
        "search": [
          "minus"
        ],
        "code": 45,
        "from": 61544,
        "css": "minus"
      },
      {
        "search": [
          "minus"
        ],
        "code": 10134,
        "from": 61526,
        "css": "minus-circle"
      },
      {
        "search": [
          "help",
          "question"
        ],
        "code": 59140,
        "from": 61529,
        "css": "help-circle"
      },
      {
        "search": [
          "info"
        ],
        "code": 59141,
        "from": 61530,
        "css": "info-circle"
      },
      {
        "search": [
          "home"
        ],
        "code": 8962,
        "from": 61461,
        "css": "home"
      },
      {
        "search": [
          "link",
          "url"
        ],
        "code": 128279,
        "from": 61582,
        "css": "link"
      },
      {
        "search": [
          "lock"
        ],
        "code": 128274,
        "from": 61475,
        "css": "lock"
      },
      {
        "search": [
          "pin",
          "pushpin"
        ],
        "code": 128204,
        "from": 61581,
        "css": "pin"
      },
      {
        "search": [
          "eye",
          "subscribe"
        ],
        "code": 59146,
        "from": 61550,
        "css": "eye"
      },
      {
        "search": [
          "eye",
          "unsubscribe"
        ],
        "code": 59147,
        "from": 61552,
        "css": "eye-off"
      },
      {
        "search": [
          "tag",
          "category",
          "price",
          "offer"
        ],
        "code": 59148,
        "from": 61483,
        "css": "tag"
      },
      {
        "search": [
          "tag",
          "category",
          "price",
          "offer"
        ],
        "code": 59149,
        "from": 61484,
        "css": "tags"
      },
      {
        "search": [
          "bookmark"
        ],
        "code": 128278,
        "from": 61486,
        "css": "bookmark"
      },
      {
        "search": [
          "flag"
        ],
        "code": 9873,
        "from": 61476,
        "css": "flag"
      },
      {
        "search": [
          "thumbs",
          "up",
          "like",
          "vote"
        ],
        "code": 128077,
        "from": 61575,
        "css": "thumbs-up"
      },
      {
        "search": [
          "thumbs",
          "down",
          "unlike",
          "vote"
        ],
        "code": 128078,
        "from": 61576,
        "css": "thumbs-down"
      },
      {
        "search": [
          "download"
        ],
        "code": 128229,
        "from": 61465,
        "css": "download"
      },
      {
        "search": [
          "upload"
        ],
        "code": 128228,
        "from": 61587,
        "css": "upload"
      },
      {
        "search": [
          "forward"
        ],
        "code": 10150,
        "from": 61540,
        "css": "forward"
      },
      {
        "search": [
          "export",
          "share"
        ],
        "code": 59157,
        "from": 61509,
        "css": "export"
      },
      {
        "search": [
          "pencil",
          "write",
          "reply",
          "edit"
        ],
        "code": 9998,
        "from": 61504,
        "css": "pencil"
      },
      {
        "search": [
          "pencil",
          "write",
          "reply",
          "edit"
        ],
        "code": 9997,
        "from": 61508,
        "css": "edit"
      },
      {
        "search": [
          "print"
        ],
        "code": 59158,
        "from": 61487,
        "css": "print"
      },
      {
        "search": [
          "retweet",
          "twitter"
        ],
        "code": 59159,
        "from": 61561,
        "css": "retweet"
      },
      {
        "search": [
          "comment",
          "reply",
          "write"
        ],
        "code": 59160,
        "from": 61557,
        "css": "comment"
      },
      {
        "search": [
          "chat",
          "talk"
        ],
        "code": 59168,
        "from": 61574,
        "css": "chat"
      },
      {
        "search": [
          "attention",
          "warning",
          "alert"
        ],
        "code": 9888,
        "from": 61553,
        "css": "attention"
      },
      {
        "search": [
          "attention",
          "warning",
          "alert"
        ],
        "code": 10071,
        "from": 61546,
        "css": "attention-circle"
      },
      {
        "search": [
          "location",
          "mark",
          "marker"
        ],
        "code": 59172,
        "from": 61505,
        "css": "location"
      },
      {
        "search": [
          "trash",
          "delete"
        ],
        "code": 59177,
        "from": 61460,
        "css": "trash"
      },
      {
        "search": [
          "doc",
          "article"
        ],
        "code": 128196,
        "from": 61462,
        "css": "doc"
      },
      {
        "search": [
          "folder"
        ],
        "code": 128193,
        "from": 61563,
        "css": "folder"
      },
      {
        "search": [
          "folder"
        ],
        "code": 128194,
        "from": 61564,
        "css": "folder-open"
      },
      {
        "search": [
          "settings",
          "cog",
          "gear"
        ],
        "code": 9881,
        "from": 61459,
        "css": "cog"
      },
      {
        "search": [
          "settings",
          "cog",
          "gear"
        ],
        "code": 9967,
        "from": 61573,
        "css": "cog-alt"
      },
      {
        "search": [
          "basket",
          "shopping",
          "cart"
        ],
        "code": 59197,
        "from": 61562,
        "css": "basket"
      },
      {
        "search": [
          "calendar",
          "date"
        ],
        "code": 128197,
        "from": 61555,
        "css": "calendar"
      },
      {
        "search": [
          "login",
          "signin",
          "enter"
        ],
        "code": 59200,
        "from": 61584,
        "css": "login"
      },
      {
        "search": [
          "logout",
          "signout",
          "exit"
        ],
        "code": 59201,
        "from": 61579,
        "css": "logout"
      },
      {
        "search": [
          "volume",
          "sound",
          "mute"
        ],
        "code": 128263,
        "from": 61478,
        "css": "volume-off"
      },
      {
        "search": [
          "volume",
          "sound"
        ],
        "code": 128265,
        "from": 61479,
        "css": "volume-down"
      },
      {
        "search": [
          "volume",
          "sound"
        ],
        "code": 128266,
        "from": 61480,
        "css": "volume-up"
      },
      {
        "search": [
          "sound",
          "music",
          "headphones"
        ],
        "code": 127911,
        "from": 61477,
        "css": "headphones"
      },
      {
        "search": [
          "clock",
          "time"
        ],
        "code": 128340,
        "from": 61463,
        "css": "clock"
      },
      {
        "search": [
          "block",
          "deny"
        ],
        "code": 128683,
        "from": 61534,
        "css": "block"
      },
      {
        "search": [
          "resize",
          "fullscreen"
        ],
        "code": 59204,
        "from": 61541,
        "css": "resize-full"
      },
      {
        "search": [
          "resize"
        ],
        "code": 59206,
        "from": 61542,
        "css": "resize-small"
      },
      {
        "search": [
          "resize"
        ],
        "code": 11020,
        "from": 61565,
        "css": "resize-vertical"
      },
      {
        "search": [
          "resize"
        ],
        "code": 11021,
        "from": 61566,
        "css": "resize-horizontal"
      },
      {
        "search": [
          "move"
        ],
        "code": 61511,
        "css": "move"
      },
      {
        "search": [
          "zoom. scale",
          "in"
        ],
        "code": 59216,
        "from": 61454,
        "css": "zoom-in"
      },
      {
        "search": [
          "zoom. scale",
          "out"
        ],
        "code": 59217,
        "from": 61456,
        "css": "zoom-out"
      },
      {
        "search": [
          "arrow",
          "down",
          "download"
        ],
        "code": 59224,
        "from": 61466,
        "css": "down-circle2"
      },
      {
        "search": [
          "arrow",
          "up",
          "upload"
        ],
        "code": 59227,
        "from": 61467,
        "css": "up-circle2"
      },
      {
        "search": [
          "arrow",
          "down"
        ],
        "code": 59228,
        "from": 61560,
        "css": "down-open"
      },
      {
        "search": [
          "arrow",
          "left"
        ],
        "code": 59229,
        "from": 61523,
        "css": "left-open"
      },
      {
        "search": [
          "arrow",
          "right"
        ],
        "code": 59230,
        "from": 61524,
        "css": "right-open"
      },
      {
        "search": [
          "arrow",
          "up"
        ],
        "code": 59231,
        "from": 61559,
        "css": "up-open"
      },
      {
        "search": [
          "arrow",
          "down"
        ],
        "code": 8595,
        "from": 61539,
        "css": "down"
      },
      {
        "search": [
          "arrow",
          "left"
        ],
        "code": 8592,
        "from": 61536,
        "css": "left"
      },
      {
        "search": [
          "arrow",
          "right"
        ],
        "code": 8594,
        "from": 61537,
        "css": "right"
      },
      {
        "search": [
          "arrow",
          "up"
        ],
        "code": 8593,
        "from": 61538,
        "css": "up"
      },
      {
        "search": [
          "reload",
          "redo",
          "repeat"
        ],
        "code": 10227,
        "from": 61470,
        "css": "cw"
      },
      {
        "search": [
          "reload",
          "refresh",
          "update"
        ],
        "code": 59232,
        "from": 61473,
        "css": "arrows-cw"
      },
      {
        "search": [
          "shuffle"
        ],
        "code": 128256,
        "from": 61556,
        "css": "shuffle"
      },
      {
        "search": [
          "play",
          "player"
        ],
        "code": 9654,
        "from": 61515,
        "css": "play"
      },
      {
        "search": [
          "play",
          "player"
        ],
        "code": 59233,
        "from": 61469,
        "css": "play-circle2"
      },
      {
        "search": [
          "stop",
          "player"
        ],
        "code": 9642,
        "from": 61517,
        "css": "stop"
      },
      {
        "search": [
          "pause",
          "player"
        ],
        "code": 9097,
        "from": 61516,
        "css": "pause"
      },
      {
        "search": [
          "right",
          "player"
        ],
        "code": 9197,
        "from": 61521,
        "css": "to-end"
      },
      {
        "search": [
          "right",
          "player"
        ],
        "code": 59234,
        "from": 61520,
        "css": "to-end-alt"
      },
      {
        "search": [
          "left",
          "player"
        ],
        "code": 9198,
        "from": 61512,
        "css": "to-start"
      },
      {
        "search": [
          "left",
          "player"
        ],
        "code": 59235,
        "from": 61513,
        "css": "to-start-alt"
      },
      {
        "search": [
          "right",
          "player"
        ],
        "code": 9193,
        "from": 61518,
        "css": "fast-fw"
      },
      {
        "search": [
          "left",
          "player"
        ],
        "code": 9194,
        "from": 61514,
        "css": "fast-bw"
      },
      {
        "search": [
          "eject",
          "player"
        ],
        "code": 11983,
        "from": 61522,
        "css": "eject"
      },
      {
        "search": [
          "target"
        ],
        "code": 127919,
        "from": 61531,
        "css": "target"
      },
      {
        "search": [
          "broadcast",
          "wifi",
          "signal"
        ],
        "code": 128246,
        "from": 61458,
        "css": "signal"
      },
      {
        "search": [
          "top",
          "trophy",
          "prize",
          "award"
        ],
        "code": 127945,
        "from": 61585,
        "css": "award"
      },
      {
        "search": [
          "inbox"
        ],
        "code": 59255,
        "from": 61468,
        "css": "inbox"
      },
      {
        "search": [
          "flight",
          "plane",
          "airplane"
        ],
        "code": 9992,
        "from": 61554,
        "css": "flight"
      },
      {
        "search": [
          "leaf"
        ],
        "code": 127810,
        "from": 61548,
        "css": "leaf"
      },
      {
        "search": [
          "editor",
          "font"
        ],
        "code": 59257,
        "from": 61489,
        "css": "font"
      },
      {
        "search": [
          "editor",
          "bold"
        ],
        "code": 59258,
        "from": 61490,
        "css": "bold"
      },
      {
        "search": [
          "editor",
          "italic"
        ],
        "code": 59259,
        "from": 61491,
        "css": "italic"
      },
      {
        "search": [
          "editor",
          "height"
        ],
        "code": 59260,
        "from": 61492,
        "css": "text-height"
      },
      {
        "search": [
          "editor",
          "width"
        ],
        "code": 59261,
        "from": 61493,
        "css": "text-width"
      },
      {
        "search": [
          "editor",
          "align",
          "left"
        ],
        "code": 59262,
        "from": 61494,
        "css": "align-left"
      },
      {
        "search": [
          "editor",
          "align",
          "center"
        ],
        "code": 59263,
        "from": 61495,
        "css": "align-center"
      },
      {
        "search": [
          "editor",
          "align",
          "right"
        ],
        "code": 59264,
        "from": 61496,
        "css": "align-right"
      },
      {
        "search": [
          "editor",
          "align",
          "justify"
        ],
        "code": 59265,
        "from": 61497,
        "css": "align-justify"
      },
      {
        "search": [
          "editor",
          "list"
        ],
        "code": 59266,
        "from": 61498,
        "css": "list"
      },
      {
        "search": [
          "editor",
          "indent"
        ],
        "code": 59267,
        "from": 61499,
        "css": "indent-left"
      },
      {
        "search": [
          "editor",
          "indent"
        ],
        "code": 59268,
        "from": 61500,
        "css": "indent-right"
      },
      {
        "search": [
          "off"
        ],
        "code": 59278,
        "from": 61457,
        "css": "off"
      },
      {
        "search": [
          "road"
        ],
        "code": 59279,
        "from": 61464,
        "css": "road"
      },
      {
        "search": [
          "list"
        ],
        "code": 59280,
        "from": 61474,
        "css": "list-alt"
      },
      {
        "search": [
          "qrcode"
        ],
        "code": 59281,
        "from": 61481,
        "css": "qrcode"
      },
      {
        "search": [
          "barcode"
        ],
        "code": 59282,
        "from": 61482,
        "css": "barcode"
      },
      {
        "search": [
          "book"
        ],
        "code": 128213,
        "from": 61485,
        "css": "book"
      },
      {
        "search": [
          "ajust"
        ],
        "code": 59283,
        "from": 61506,
        "css": "ajust"
      },
      {
        "search": [
          "tint"
        ],
        "code": 59284,
        "from": 61507,
        "css": "tint"
      },
      {
        "search": [
          "check"
        ],
        "code": 9745,
        "from": 61510,
        "css": "check"
      },
      {
        "search": [
          "asterisk"
        ],
        "code": 10033,
        "from": 61545,
        "css": "asterisk"
      },
      {
        "search": [
          "gift",
          "present",
          "package",
          "box"
        ],
        "code": 127873,
        "from": 61547,
        "css": "gift"
      },
      {
        "search": [
          "fire"
        ],
        "code": 128293,
        "from": 61549,
        "css": "fire"
      },
      {
        "search": [
          "magnet"
        ],
        "code": 59297,
        "from": 61558,
        "css": "magnet"
      },
      {
        "search": [
          "chart",
          "bar",
          "diagram"
        ],
        "code": 128202,
        "from": 61568,
        "css": "chart-bar"
      },
      {
        "search": [
          "key"
        ],
        "code": 128273,
        "from": 61572,
        "css": "key"
      },
      {
        "search": [
          "github"
        ],
        "code": 62208,
        "from": 61586,
        "css": "github"
      },
      {
        "search": [
          "twitter"
        ],
        "code": 62212,
        "from": 61569,
        "css": "twitter"
      },
      {
        "search": [
          "facebook"
        ],
        "code": 62216,
        "from": 61570,
        "css": "facebook"
      },
      {
        "code": 62220,
        "from": 61580,
        "css": "linkedin"
      },
      {
        "code": 127819,
        "from": 61588,
        "css": "lemon"
      }
    ],
    "transform": {
      "rescale": 1.052631579,
      "baseline": 0.5,
      "offset": -0.05
    },
    "id": 1
  },
  {
    "font": {
      "fontname": "iconic",
      "descent": 200,
      "copyright": "Copyright (C) 2012 by P.J. Onori",
      "familyname": "Iconic",
      "weight": "Medium",
      "version": "1.0",
      "fullname": "Iconic",
      "ascent": 800
    },
    "meta": {
      "github": "https://github.com/somerandomdude/Iconic",
      "licence_url": "http://scripts.sil.org/OFL",
      "licence": "SIL",
      "author": "P.J. Onori",
      "twitter": "http://twitter.com/somerandomdude",
      "css_prefix": "icon-",
      "homepage": "http://somerandomdude.com/work/iconic/",
      "email": "pj@somerandomdude.com",
      "columns": 4
    },
    "glyphs": [
      {
        "search": [
          "search",
          "find"
        ],
        "code": 128270,
        "file": "magnifying_glass",
        "css": "search"
      },
      {
        "search": [
          "mail",
          "email"
        ],
        "code": 9993,
        "file": "mail",
        "css": "mail"
      },
      {
        "search": [
          "heart"
        ],
        "code": 9829,
        "file": "heart_fill",
        "css": "heart"
      },
      {
        "search": [
          "heart"
        ],
        "code": 9825,
        "file": "heart_stroke",
        "css": "heart-empty"
      },
      {
        "search": [
          "star"
        ],
        "code": 9733,
        "file": "star",
        "css": "star"
      },
      {
        "search": [
          "profile",
          "contact",
          "user"
        ],
        "code": 128100,
        "file": "user",
        "css": "user"
      },
      {
        "search": [
          "movie",
          "video",
          "film"
        ],
        "code": 127916,
        "file": "movie",
        "css": "video"
      },
      {
        "search": [
          "image",
          "picture",
          "photo"
        ],
        "code": 127748,
        "file": "image",
        "css": "picture"
      },
      {
        "search": [
          "camera",
          "photo"
        ],
        "code": 128247,
        "file": "camera",
        "css": "camera"
      },
      {
        "search": [
          "ok",
          true,
          "check",
          "mark"
        ],
        "code": 10003,
        "file": "check",
        "css": "ok"
      },
      {
        "search": [
          "ok",
          true,
          "check",
          "mark"
        ],
        "code": 10004,
        "file": "check_alt",
        "css": "ok-circle"
      },
      {
        "search": [
          "close",
          "cancel",
          "reject"
        ],
        "code": 10005,
        "file": "x",
        "css": "cancel"
      },
      {
        "search": [
          "close",
          "cancel",
          "reject"
        ],
        "code": 10006,
        "file": "x_alt",
        "css": "cancel-circle"
      },
      {
        "search": [
          "plus"
        ],
        "code": 43,
        "file": "plus",
        "css": "plus"
      },
      {
        "search": [
          "plus"
        ],
        "code": 10133,
        "file": "plus_alt",
        "css": "plus-circle"
      },
      {
        "search": [
          "minus"
        ],
        "code": 45,
        "file": "minus",
        "css": "minus"
      },
      {
        "search": [
          "minus"
        ],
        "code": 10134,
        "file": "minus_alt",
        "css": "minus-circle"
      },
      {
        "search": [
          "help",
          "question"
        ],
        "code": 10067,
        "file": "question_mark",
        "css": "help"
      },
      {
        "search": [
          "info"
        ],
        "code": 8505,
        "file": "info",
        "css": "info"
      },
      {
        "search": [
          "home"
        ],
        "code": 8962,
        "file": "home",
        "css": "home"
      },
      {
        "search": [
          "link",
          "url",
          "address"
        ],
        "code": 128279,
        "file": "link",
        "css": "link"
      },
      {
        "search": [
          "attach",
          "clip",
          "paperclip"
        ],
        "code": 128206,
        "file": "paperclip",
        "css": "attach"
      },
      {
        "search": [
          "lock"
        ],
        "code": 128274,
        "file": "lock_fill",
        "css": "lock"
      },
      {
        "search": [
          "lock"
        ],
        "code": 59144,
        "file": "lock_stroke",
        "css": "lock-empty"
      },
      {
        "search": [
          "lock",
          "unlock"
        ],
        "code": 128275,
        "file": "unlock_fill",
        "css": "lock-open"
      },
      {
        "search": [
          "lock",
          "unlock"
        ],
        "code": 59145,
        "file": "unlock_stroke",
        "css": "lock-open-empty"
      },
      {
        "search": [
          "pin",
          "pushpin"
        ],
        "code": 128204,
        "from": 61581,
        "css": "pin",
        "file": "pin"
      },
      {
        "search": [
          "eye",
          "subscribe"
        ],
        "code": 59146,
        "file": "eye",
        "css": "eye"
      },
      {
        "search": [
          "tag",
          "price",
          "offer"
        ],
        "code": 59148,
        "file": "tag_fill",
        "css": "tag"
      },
      {
        "search": [
          "tag",
          "price",
          "offer"
        ],
        "code": 59150,
        "file": "tag_stroke",
        "css": "tag-empty"
      },
      {
        "search": [
          "download"
        ],
        "code": 128229,
        "file": "download",
        "css": "download"
      },
      {
        "search": [
          "upload"
        ],
        "code": 128228,
        "file": "upload",
        "css": "upload"
      },
      {
        "search": [
          "download",
          "cloud"
        ],
        "code": 59152,
        "file": "cloud_download",
        "css": "download-cloud"
      },
      {
        "search": [
          "upload",
          "cloud"
        ],
        "code": 59153,
        "file": "cloud_upload",
        "css": "upload-cloud"
      },
      {
        "search": [
          "quote"
        ],
        "code": 10077,
        "file": "left_quote",
        "css": "quote-left"
      },
      {
        "search": [
          "quote"
        ],
        "code": 10078,
        "file": "right_quote",
        "css": "quote-right"
      },
      {
        "search": [
          "quote"
        ],
        "code": 10075,
        "file": "left_quote_alt",
        "css": "quote-left-alt"
      },
      {
        "search": [
          "quote"
        ],
        "code": 10076,
        "file": "right_quote_alt",
        "css": "quote-right-alt"
      },
      {
        "search": [
          "pencil",
          "write",
          "reply",
          "edit"
        ],
        "code": 9998,
        "file": "pen_alt_stroke",
        "css": "pencil"
      },
      {
        "search": [
          "pencil",
          "write",
          "reply",
          "edit"
        ],
        "code": 9999,
        "file": "pen_alt_fill",
        "css": "pencil-neg"
      },
      {
        "search": [
          "pencil",
          "write",
          "reply",
          "edit"
        ],
        "code": 10000,
        "file": "pen_alt2",
        "css": "pencil-alt"
      },
      {
        "search": [
          "undo",
          "return",
          "back"
        ],
        "code": 8630,
        "file": "undo",
        "css": "undo"
      },
      {
        "search": [
          "comment",
          "reply",
          "write"
        ],
        "code": 59160,
        "file": "comment_stroke",
        "css": "comment"
      },
      {
        "search": [
          "comment",
          "reply",
          "write"
        ],
        "code": 59161,
        "file": "comment_fill",
        "css": "comment-inv"
      },
      {
        "search": [
          "comment",
          "reply",
          "write"
        ],
        "code": 59162,
        "file": "comment_alt1_stroke",
        "css": "comment-alt"
      },
      {
        "search": [
          "comment",
          "reply",
          "write"
        ],
        "code": 59163,
        "file": "comment_alt1_fill",
        "css": "comment-inv-alt"
      },
      {
        "search": [
          "comment",
          "reply",
          "write"
        ],
        "code": 59164,
        "file": "comment_alt2_stroke",
        "css": "comment-alt2"
      },
      {
        "search": [
          "comment",
          "reply",
          "write"
        ],
        "code": 59165,
        "file": "comment_alt2_fill",
        "css": "comment-inv-alt2"
      },
      {
        "search": [
          "chat",
          "talk"
        ],
        "code": 59168,
        "file": "chat_alt_stroke",
        "css": "chat"
      },
      {
        "search": [
          "chat",
          "talk"
        ],
        "code": 59169,
        "file": "chat_alt_fill",
        "css": "chat-inv"
      },
      {
        "search": [
          "location",
          "mark",
          "marker"
        ],
        "code": 59172,
        "file": "map_pin_fill",
        "css": "location"
      },
      {
        "search": [
          "location",
          "mark",
          "marker"
        ],
        "code": 59173,
        "file": "map_pin_stroke",
        "css": "location-inv"
      },
      {
        "search": [
          "location",
          "mark",
          "marker"
        ],
        "code": 59174,
        "file": "map_pin_alt",
        "css": "location-alt"
      },
      {
        "search": [
          "compass"
        ],
        "code": 59176,
        "file": "compass",
        "css": "compass"
      },
      {
        "search": [
          "trash",
          "delete"
        ],
        "code": 59177,
        "file": "trash_fill",
        "css": "trash"
      },
      {
        "search": [
          "trash",
          "delete"
        ],
        "code": 59178,
        "file": "trash_stroke",
        "css": "trash-empty"
      },
      {
        "search": [
          "doc",
          "article"
        ],
        "code": 59184,
        "file": "document_alt_stroke",
        "css": "doc"
      },
      {
        "search": [
          "doc",
          "article"
        ],
        "code": 59185,
        "file": "document_alt_fill",
        "css": "doc-inv"
      },
      {
        "search": [
          "doc",
          "article"
        ],
        "code": 59186,
        "file": "document_stroke",
        "css": "doc-alt"
      },
      {
        "search": [
          "doc",
          "article"
        ],
        "code": 59187,
        "file": "document_fill",
        "css": "doc-inv-alt"
      },
      {
        "search": [
          "document",
          "article"
        ],
        "code": 59188,
        "file": "article",
        "css": "article"
      },
      {
        "search": [
          "document",
          "article",
          "more"
        ],
        "code": 59189,
        "file": "read_more",
        "css": "article-alt"
      },
      {
        "search": [
          "book",
          "doc"
        ],
        "code": 128214,
        "file": "book_alt2",
        "css": "book-open"
      },
      {
        "search": [
          "folder"
        ],
        "code": 128193,
        "file": "folder_fill",
        "css": "folder"
      },
      {
        "search": [
          "folder"
        ],
        "code": 128194,
        "file": "folder_stroke",
        "css": "folder-empty"
      },
      {
        "search": [
          "box",
          "archive",
          "package"
        ],
        "code": 128230,
        "file": "box",
        "css": "box"
      },
      {
        "search": [
          "rss"
        ],
        "code": 59194,
        "file": "rss_alt",
        "css": "rss"
      },
      {
        "search": [
          "rss"
        ],
        "code": 59195,
        "file": "rss",
        "css": "rss-alt"
      },
      {
        "search": [
          "settings",
          "cog",
          "gear"
        ],
        "code": 9881,
        "file": "cog",
        "css": "cog"
      },
      {
        "search": [
          "settings",
          "wrench"
        ],
        "code": 128295,
        "file": "wrench",
        "css": "wrench"
      },
      {
        "search": [
          "share"
        ],
        "code": 59196,
        "file": "share",
        "css": "share"
      },
      {
        "search": [
          "calendar",
          "date"
        ],
        "code": 128197,
        "file": "calendar_alt_stroke",
        "css": "calendar"
      },
      {
        "search": [
          "calendar",
          "date"
        ],
        "code": 59198,
        "file": "calendar_alt_fill",
        "css": "calendar-inv"
      },
      {
        "search": [
          "calendar",
          "date"
        ],
        "code": 128198,
        "file": "calendar",
        "css": "calendar-alt"
      },
      {
        "search": [
          "mic"
        ],
        "code": 127908,
        "file": "mic",
        "css": "mic"
      },
      {
        "search": [
          "volume",
          "sound",
          "mute"
        ],
        "code": 128263,
        "file": "volume_mute",
        "css": "volume-off"
      },
      {
        "search": [
          "volume",
          "sound"
        ],
        "code": 128266,
        "file": "volume",
        "css": "volume-up"
      },
      {
        "search": [
          "sound",
          "music",
          "headphones"
        ],
        "code": 127911,
        "file": "headphones",
        "css": "headphones"
      },
      {
        "search": [
          "clock",
          "time"
        ],
        "code": 128340,
        "file": "clock",
        "css": "clock"
      },
      {
        "search": [
          "idea",
          "lamp",
          "light"
        ],
        "code": 128161,
        "file": "lightbulb",
        "css": "lamp"
      },
      {
        "search": [
          "block",
          "deny"
        ],
        "code": 128683,
        "file": "denied",
        "css": "block"
      },
      {
        "search": [
          "resize",
          "fullscreen"
        ],
        "code": 59204,
        "file": "fullscreen",
        "css": "resize-full"
      },
      {
        "search": [
          "resize",
          "fullscreen"
        ],
        "code": 59205,
        "file": "fullscreen_alt",
        "css": "resize-full-alt"
      },
      {
        "search": [
          "resize"
        ],
        "code": 59206,
        "file": "fullscreen_exit",
        "css": "resize-small"
      },
      {
        "search": [
          "resize"
        ],
        "code": 59207,
        "file": "fullscreen_exit_alt",
        "css": "resize-small-alt"
      },
      {
        "search": [
          "resize"
        ],
        "code": 11020,
        "file": "move_vertical",
        "css": "resize-vertical"
      },
      {
        "search": [
          "resize"
        ],
        "code": 11021,
        "file": "move_horizontal",
        "css": "resize-horizontal"
      },
      {
        "search": [
          "move"
        ],
        "code": 59210,
        "file": "move",
        "css": "move"
      },
      {
        "search": [
          "popup",
          "window"
        ],
        "code": 59212,
        "file": "new_window",
        "css": "popup"
      },
      {
        "search": [
          "arrow",
          "down"
        ],
        "code": 8595,
        "file": "arrow_down",
        "css": "down"
      },
      {
        "search": [
          "arrow",
          "left"
        ],
        "code": 8592,
        "file": "arrow_left",
        "css": "left"
      },
      {
        "search": [
          "arrow",
          "right"
        ],
        "code": 8594,
        "file": "arrow_right",
        "css": "right"
      },
      {
        "search": [
          "arrow",
          "up"
        ],
        "code": 8593,
        "file": "arrow_up",
        "css": "up"
      },
      {
        "search": [
          "arrow",
          "down"
        ],
        "code": 58532,
        "file": "arrow_down_alt1",
        "css": "down-circle"
      },
      {
        "search": [
          "arrow",
          "left"
        ],
        "code": 58529,
        "file": "arrow_left_alt1",
        "css": "left-circle"
      },
      {
        "search": [
          "arrow",
          "right"
        ],
        "code": 58530,
        "file": "arrow_right_alt1",
        "css": "right-circle"
      },
      {
        "search": [
          "arrow",
          "up"
        ],
        "code": 58531,
        "file": "arrow_up_alt1",
        "css": "up-circle"
      },
      {
        "search": [
          "arrow",
          "reload",
          "redo",
          "repeat"
        ],
        "code": 10227,
        "file": "reload",
        "css": "cw"
      },
      {
        "search": [
          "arrow",
          "loop",
          "reload",
          "refresh"
        ],
        "code": 128260,
        "file": "loop_alt2",
        "css": "loop"
      },
      {
        "search": [
          "arrow",
          "loop",
          "reload",
          "refresh"
        ],
        "code": 128257,
        "file": "loop_alt3",
        "css": "loop-alt"
      },
      {
        "search": [
          "arrow",
          "exchange",
          "transfer"
        ],
        "code": 8644,
        "file": "transfer",
        "css": "exchange"
      },
      {
        "search": [
          "arrow",
          "split",
          "fork"
        ],
        "code": 9095,
        "file": "fork",
        "css": "split"
      },
      {
        "search": [
          "arrow"
        ],
        "code": 10549,
        "file": "curved_arrow",
        "css": "arrow-curved"
      },
      {
        "search": [
          "play",
          "player"
        ],
        "code": 9654,
        "file": "play",
        "css": "play"
      },
      {
        "search": [
          "play",
          "player"
        ],
        "code": 57416,
        "file": "play_alt",
        "css": "play-circle2"
      },
      {
        "search": [
          "stop",
          "player"
        ],
        "code": 9642,
        "file": "stop",
        "css": "stop"
      },
      {
        "search": [
          "pause",
          "player"
        ],
        "code": 9097,
        "file": "pause",
        "css": "pause"
      },
      {
        "search": [
          "left",
          "player"
        ],
        "code": 9198,
        "file": "first",
        "css": "to-start"
      },
      {
        "search": [
          "right",
          "player"
        ],
        "code": 9197,
        "file": "last",
        "css": "to-end"
      },
      {
        "search": [
          "eject",
          "player"
        ],
        "code": 9167,
        "file": "eject",
        "css": "eject"
      },
      {
        "search": [
          "target"
        ],
        "code": 127919,
        "file": "target",
        "css": "target"
      },
      {
        "search": [
          "chart",
          "bar",
          "diagram",
          "signal",
          "wifi"
        ],
        "code": 128246,
        "file": "bars_alt",
        "css": "signal"
      },
      {
        "search": [
          "top",
          "trophy",
          "prize",
          "award"
        ],
        "code": 127945,
        "file": "award_fill",
        "css": "award"
      },
      {
        "search": [
          "top",
          "trophy",
          "prize",
          "award"
        ],
        "code": 59236,
        "file": "award_stroke",
        "css": "award-empty"
      },
      {
        "search": [
          "list"
        ],
        "code": 59237,
        "file": "list",
        "css": "list"
      },
      {
        "search": [
          "list"
        ],
        "code": 59238,
        "file": "list_nested",
        "css": "list-nested"
      },
      {
        "search": [
          "battery"
        ],
        "code": 59250,
        "file": "battery_empty",
        "css": "bat-empty"
      },
      {
        "search": [
          "battery"
        ],
        "code": 59251,
        "file": "battery_half",
        "css": "bat-half"
      },
      {
        "search": [
          "battery"
        ],
        "code": 59252,
        "file": "battery_full",
        "css": "bat-full"
      },
      {
        "search": [
          "battery",
          "charge"
        ],
        "code": 59253,
        "file": "battery_charging",
        "css": "bat-charge"
      },
      {
        "search": [
          "mobile",
          "iphone"
        ],
        "code": 128241,
        "file": "iphone",
        "css": "mobile"
      },
      {
        "search": [
          "cd",
          "vinyl"
        ],
        "code": 128191,
        "file": "cd",
        "css": "cd"
      },
      {
        "search": [
          "equalizer"
        ],
        "code": 59285,
        "file": "equalizer",
        "css": "equalizer"
      },
      {
        "search": [
          "cursor",
          "arrow"
        ],
        "code": 59286,
        "file": "cursor",
        "css": "cursor"
      },
      {
        "search": [
          "aperture"
        ],
        "code": 59287,
        "file": "aperture",
        "css": "aperture"
      },
      {
        "search": [
          "aperture"
        ],
        "code": 59288,
        "file": "aperture_alt",
        "css": "aperture-alt"
      },
      {
        "search": [
          "steering",
          "wheel"
        ],
        "code": 59289,
        "file": "steering_wheel",
        "css": "steering-wheel"
      },
      {
        "search": [
          "book"
        ],
        "code": 128213,
        "file": "book",
        "css": "book"
      },
      {
        "search": [
          "book"
        ],
        "code": 128212,
        "file": "book_alt",
        "css": "book-alt"
      },
      {
        "search": [
          "paint",
          "brush"
        ],
        "code": 59290,
        "file": "brush",
        "css": "brush"
      },
      {
        "search": [
          "paint",
          "brush"
        ],
        "code": 59291,
        "file": "brush_alt",
        "css": "brush-alt"
      },
      {
        "search": [
          "paint",
          "eyedropper"
        ],
        "code": 59292,
        "file": "eyedropper",
        "css": "eyedropper"
      },
      {
        "search": [
          "paint",
          "layers"
        ],
        "code": 59293,
        "file": "layers",
        "css": "layers"
      },
      {
        "search": [
          "paint",
          "layers"
        ],
        "code": 59294,
        "file": "layers_alt",
        "css": "layers-alt"
      },
      {
        "search": [
          "weather",
          "sun"
        ],
        "code": 9788,
        "file": "sun_stroke",
        "css": "sun"
      },
      {
        "search": [
          "weather",
          "sun"
        ],
        "code": 9728,
        "file": "sun_fill",
        "css": "sun-inv"
      },
      {
        "search": [
          "weather",
          "cloud"
        ],
        "code": 9729,
        "file": "cloud",
        "css": "cloud"
      },
      {
        "search": [
          "weather",
          "rain"
        ],
        "code": 9926,
        "file": "rain",
        "css": "rain"
      },
      {
        "search": [
          "flash",
          "bolt"
        ],
        "code": 9889,
        "file": "bolt",
        "css": "flash"
      },
      {
        "search": [
          "moon",
          "sleep"
        ],
        "code": 9790,
        "file": "moon_stroke",
        "css": "moon"
      },
      {
        "search": [
          "moon",
          "sleep"
        ],
        "code": 59296,
        "file": "moon_fill",
        "css": "moon-inv"
      },
      {
        "search": [
          "weather",
          "umbrella"
        ],
        "code": 9730,
        "file": "umbrella",
        "css": "umbrella"
      },
      {
        "search": [
          "chart",
          "bar",
          "diagram"
        ],
        "code": 128202,
        "file": "bars",
        "css": "chart-bar"
      },
      {
        "search": [
          "chart",
          "pie",
          "diagram"
        ],
        "code": 59298,
        "file": "chart",
        "css": "chart-pie"
      },
      {
        "search": [
          "chart",
          "pie",
          "diagram"
        ],
        "code": 59299,
        "file": "chart_alt",
        "css": "chart-pie-alt"
      },
      {
        "search": [
          "key"
        ],
        "code": 9919,
        "file": "key_stroke",
        "css": "key"
      },
      {
        "search": [
          "key"
        ],
        "code": 128273,
        "file": "key_fill",
        "css": "key-inv"
      },
      {
        "search": [
          "hash"
        ],
        "code": 35,
        "file": "hash",
        "css": "hash"
      },
      {
        "search": [
          "@",
          "at"
        ],
        "code": 64,
        "file": "at",
        "css": "at"
      },
      {
        "search": [
          "pilcrow"
        ],
        "code": 182,
        "file": "pilcrow",
        "css": "pilcrow"
      },
      {
        "search": [
          "dial"
        ],
        "code": 59300,
        "file": "dial",
        "css": "dial"
      }
    ],
    "transform": {
      "rescale": 1.2,
      "baseline": 0.5,
      "offset": -0.05
    },
    "id": 2
  },
  {
    "font": {
      "fontname": "brandico",
      "version": "1.0",
      "descent": 200,
      "copyright": "(C) 2012 by Vitaly Puzrin",
      "fullname": "Brandico",
      "familyname": "Brandico",
      "ascent": 800
    },
    "meta": {
      "github": "https://github.com/fontello/brandico.font",
      "licence_url": "http://scripts.sil.org/OFL",
      "css_prefix": "icon-",
      "licence": "SIL",
      "author": "Crowdsourced, for Fontello project",
      "columns": 4
    },
    "glyphs": [
      {
        "search": [
          "facebook"
        ],
        "code": 62208,
        "meta": {
          "homepage": "http://www.alexpeattie.com/projects/justvector_icons/",
          "author": "Alex Peattie"
        },
        "file": "facebook",
        "transform": {
          "offset": 0.05
        },
        "css": "facebook"
      },
      {
        "search": [
          "facebook"
        ],
        "code": 62209,
        "meta": {
          "homepage": "http://www.alexpeattie.com/projects/justvector_icons/",
          "author": "Alex Peattie"
        },
        "file": "facebook-rect",
        "transform": {
          "offset": 0.05
        },
        "css": "facebook-rect"
      },
      {
        "search": [
          "twitter"
        ],
        "code": 62210,
        "meta": {
          "author": "Vitaly Puzrin"
        },
        "file": "twitter",
        "transform": {
          "offset": 0.05
        },
        "css": "twitter"
      },
      {
        "search": [
          "twitter"
        ],
        "code": 62211,
        "meta": {
          "author": "Vitaly Puzrin"
        },
        "file": "twitter-bird",
        "transform": {
          "rescale": 0.9,
          "offset": 0.05
        },
        "css": "twitter-bird"
      },
      {
        "search": [
          "icq"
        ],
        "code": 62212,
        "meta": {
          "author": "Vitaly Puzrin"
        },
        "file": "icq",
        "transform": {
          "offset": 0.05
        },
        "css": "icq"
      },
      {
        "search": [
          "yandex"
        ],
        "code": 62213,
        "meta": {
          "author": "Vitaly Puzrin"
        },
        "file": "yandex",
        "transform": {
          "offset": 0.05
        },
        "css": "yandex"
      },
      {
        "search": [
          "yandex"
        ],
        "code": 62214,
        "meta": {
          "author": "Vitaly Puzrin"
        },
        "file": "yandex-rect",
        "transform": {
          "offset": 0.05
        },
        "css": "yandex-rect"
      },
      {
        "search": [
          "github"
        ],
        "code": 62215,
        "meta": {
          "author": "Vitaly Puzrin"
        },
        "file": "github-text",
        "transform": {
          "offset": 0.05
        },
        "css": "github-text"
      },
      {
        "search": [
          "github"
        ],
        "code": 62216,
        "meta": {
          "author": "Vitaly Puzrin"
        },
        "file": "github",
        "transform": {
          "rescale": 0.9,
          "offset": 0.05
        },
        "css": "github"
      },
      {
        "search": [
          "google"
        ],
        "code": 62217,
        "meta": {
          "homepage": "http://www.google.com/+/business/brand-guidelines.html",
          "author": "Google"
        },
        "file": "googleplus-rect",
        "transform": {
          "offset": 0.05
        },
        "css": "googleplus-rect"
      },
      {
        "search": [
          "google"
        ],
        "code": 62218,
        "meta": {
          "homepage": "http://vk.com/help.php?page=about",
          "author": "Vkontakte"
        },
        "file": "vkontakte-rect",
        "transform": {
          "offset": 0.05
        },
        "css": "vkontakte-rect"
      },
      {
        "search": [
          "facebook"
        ],
        "code": 62219,
        "meta": {
          "homepage": "http://www.alexpeattie.com/projects/justvector_icons/",
          "author": "Alex Peattie"
        },
        "file": "skype",
        "transform": {
          "offset": 0.05
        },
        "css": "skype"
      }
    ],
    "transform": {
      "baseline": 0.5
    },
    "id": 3
  }
];